// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: query/membership/v1/membership.proto

package membershipv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MembershipQueryService_GetEmployee_FullMethodName                   = "/query.membership.v1.MembershipQueryService/GetEmployee"
	MembershipQueryService_ListEmployeesByDepartment_FullMethodName     = "/query.membership.v1.MembershipQueryService/ListEmployeesByDepartment"
	MembershipQueryService_ListEmployeesByClinic_FullMethodName         = "/query.membership.v1.MembershipQueryService/ListEmployeesByClinic"
	MembershipQueryService_ListEmployeesByOrganization_FullMethodName   = "/query.membership.v1.MembershipQueryService/ListEmployeesByOrganization"
	MembershipQueryService_CountEmployeesByDepartment_FullMethodName    = "/query.membership.v1.MembershipQueryService/CountEmployeesByDepartment"
	MembershipQueryService_CountEmployeesByClinic_FullMethodName        = "/query.membership.v1.MembershipQueryService/CountEmployeesByClinic"
	MembershipQueryService_CountEmployeesByOrganization_FullMethodName  = "/query.membership.v1.MembershipQueryService/CountEmployeesByOrganization"
	MembershipQueryService_SearchEmployeesByOrganization_FullMethodName = "/query.membership.v1.MembershipQueryService/SearchEmployeesByOrganization"
	MembershipQueryService_ListVacationsByEmployee_FullMethodName       = "/query.membership.v1.MembershipQueryService/ListVacationsByEmployee"
	MembershipQueryService_CountVacationsByEmployee_FullMethodName      = "/query.membership.v1.MembershipQueryService/CountVacationsByEmployee"
	MembershipQueryService_GetClinicHead_FullMethodName                 = "/query.membership.v1.MembershipQueryService/GetClinicHead"
	MembershipQueryService_GetDepartmentResponsible_FullMethodName      = "/query.membership.v1.MembershipQueryService/GetDepartmentResponsible"
	MembershipQueryService_ListOrgAdmins_FullMethodName                 = "/query.membership.v1.MembershipQueryService/ListOrgAdmins"
	MembershipQueryService_ListOrgDispatchers_FullMethodName            = "/query.membership.v1.MembershipQueryService/ListOrgDispatchers"
	MembershipQueryService_ListOrgHeads_FullMethodName                  = "/query.membership.v1.MembershipQueryService/ListOrgHeads"
	MembershipQueryService_ListSystemAdmins_FullMethodName              = "/query.membership.v1.MembershipQueryService/ListSystemAdmins"
)

// MembershipQueryServiceClient is the client API for MembershipQueryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MembershipQueryService exposes read methods over the employee
// projections and the role assignment projections (clinic heads,
// department responsibles, org admins/heads/dispatchers, system admins).
type MembershipQueryServiceClient interface {
	GetEmployee(ctx context.Context, in *GetEmployeeRequest, opts ...grpc.CallOption) (*GetEmployeeResponse, error)
	ListEmployeesByDepartment(ctx context.Context, in *ListEmployeesByDepartmentRequest, opts ...grpc.CallOption) (*ListEmployeesByDepartmentResponse, error)
	ListEmployeesByClinic(ctx context.Context, in *ListEmployeesByClinicRequest, opts ...grpc.CallOption) (*ListEmployeesByClinicResponse, error)
	ListEmployeesByOrganization(ctx context.Context, in *ListEmployeesByOrganizationRequest, opts ...grpc.CallOption) (*ListEmployeesByOrganizationResponse, error)
	CountEmployeesByDepartment(ctx context.Context, in *CountEmployeesByDepartmentRequest, opts ...grpc.CallOption) (*CountEmployeesByDepartmentResponse, error)
	CountEmployeesByClinic(ctx context.Context, in *CountEmployeesByClinicRequest, opts ...grpc.CallOption) (*CountEmployeesByClinicResponse, error)
	CountEmployeesByOrganization(ctx context.Context, in *CountEmployeesByOrganizationRequest, opts ...grpc.CallOption) (*CountEmployeesByOrganizationResponse, error)
	SearchEmployeesByOrganization(ctx context.Context, in *SearchEmployeesByOrganizationRequest, opts ...grpc.CallOption) (*SearchEmployeesByOrganizationResponse, error)
	ListVacationsByEmployee(ctx context.Context, in *ListVacationsByEmployeeRequest, opts ...grpc.CallOption) (*ListVacationsByEmployeeResponse, error)
	CountVacationsByEmployee(ctx context.Context, in *CountVacationsByEmployeeRequest, opts ...grpc.CallOption) (*CountVacationsByEmployeeResponse, error)
	GetClinicHead(ctx context.Context, in *GetClinicHeadRequest, opts ...grpc.CallOption) (*GetClinicHeadResponse, error)
	GetDepartmentResponsible(ctx context.Context, in *GetDepartmentResponsibleRequest, opts ...grpc.CallOption) (*GetDepartmentResponsibleResponse, error)
	ListOrgAdmins(ctx context.Context, in *ListOrgAdminsRequest, opts ...grpc.CallOption) (*ListOrgAdminsResponse, error)
	ListOrgDispatchers(ctx context.Context, in *ListOrgDispatchersRequest, opts ...grpc.CallOption) (*ListOrgDispatchersResponse, error)
	ListOrgHeads(ctx context.Context, in *ListOrgHeadsRequest, opts ...grpc.CallOption) (*ListOrgHeadsResponse, error)
	ListSystemAdmins(ctx context.Context, in *ListSystemAdminsRequest, opts ...grpc.CallOption) (*ListSystemAdminsResponse, error)
}

type membershipQueryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipQueryServiceClient(cc grpc.ClientConnInterface) MembershipQueryServiceClient {
	return &membershipQueryServiceClient{cc}
}

func (c *membershipQueryServiceClient) GetEmployee(ctx context.Context, in *GetEmployeeRequest, opts ...grpc.CallOption) (*GetEmployeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmployeeResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_GetEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) ListEmployeesByDepartment(ctx context.Context, in *ListEmployeesByDepartmentRequest, opts ...grpc.CallOption) (*ListEmployeesByDepartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEmployeesByDepartmentResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_ListEmployeesByDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) ListEmployeesByClinic(ctx context.Context, in *ListEmployeesByClinicRequest, opts ...grpc.CallOption) (*ListEmployeesByClinicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEmployeesByClinicResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_ListEmployeesByClinic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) ListEmployeesByOrganization(ctx context.Context, in *ListEmployeesByOrganizationRequest, opts ...grpc.CallOption) (*ListEmployeesByOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEmployeesByOrganizationResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_ListEmployeesByOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) CountEmployeesByDepartment(ctx context.Context, in *CountEmployeesByDepartmentRequest, opts ...grpc.CallOption) (*CountEmployeesByDepartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountEmployeesByDepartmentResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_CountEmployeesByDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) CountEmployeesByClinic(ctx context.Context, in *CountEmployeesByClinicRequest, opts ...grpc.CallOption) (*CountEmployeesByClinicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountEmployeesByClinicResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_CountEmployeesByClinic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) CountEmployeesByOrganization(ctx context.Context, in *CountEmployeesByOrganizationRequest, opts ...grpc.CallOption) (*CountEmployeesByOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountEmployeesByOrganizationResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_CountEmployeesByOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) SearchEmployeesByOrganization(ctx context.Context, in *SearchEmployeesByOrganizationRequest, opts ...grpc.CallOption) (*SearchEmployeesByOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchEmployeesByOrganizationResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_SearchEmployeesByOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) ListVacationsByEmployee(ctx context.Context, in *ListVacationsByEmployeeRequest, opts ...grpc.CallOption) (*ListVacationsByEmployeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVacationsByEmployeeResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_ListVacationsByEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) CountVacationsByEmployee(ctx context.Context, in *CountVacationsByEmployeeRequest, opts ...grpc.CallOption) (*CountVacationsByEmployeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountVacationsByEmployeeResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_CountVacationsByEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) GetClinicHead(ctx context.Context, in *GetClinicHeadRequest, opts ...grpc.CallOption) (*GetClinicHeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClinicHeadResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_GetClinicHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) GetDepartmentResponsible(ctx context.Context, in *GetDepartmentResponsibleRequest, opts ...grpc.CallOption) (*GetDepartmentResponsibleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepartmentResponsibleResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_GetDepartmentResponsible_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) ListOrgAdmins(ctx context.Context, in *ListOrgAdminsRequest, opts ...grpc.CallOption) (*ListOrgAdminsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrgAdminsResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_ListOrgAdmins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) ListOrgDispatchers(ctx context.Context, in *ListOrgDispatchersRequest, opts ...grpc.CallOption) (*ListOrgDispatchersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrgDispatchersResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_ListOrgDispatchers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) ListOrgHeads(ctx context.Context, in *ListOrgHeadsRequest, opts ...grpc.CallOption) (*ListOrgHeadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrgHeadsResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_ListOrgHeads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipQueryServiceClient) ListSystemAdmins(ctx context.Context, in *ListSystemAdminsRequest, opts ...grpc.CallOption) (*ListSystemAdminsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSystemAdminsResponse)
	err := c.cc.Invoke(ctx, MembershipQueryService_ListSystemAdmins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipQueryServiceServer is the server API for MembershipQueryService service.
// All implementations must embed UnimplementedMembershipQueryServiceServer
// for forward compatibility.
//
// MembershipQueryService exposes read methods over the employee
// projections and the role assignment projections (clinic heads,
// department responsibles, org admins/heads/dispatchers, system admins).
type MembershipQueryServiceServer interface {
	GetEmployee(context.Context, *GetEmployeeRequest) (*GetEmployeeResponse, error)
	ListEmployeesByDepartment(context.Context, *ListEmployeesByDepartmentRequest) (*ListEmployeesByDepartmentResponse, error)
	ListEmployeesByClinic(context.Context, *ListEmployeesByClinicRequest) (*ListEmployeesByClinicResponse, error)
	ListEmployeesByOrganization(context.Context, *ListEmployeesByOrganizationRequest) (*ListEmployeesByOrganizationResponse, error)
	CountEmployeesByDepartment(context.Context, *CountEmployeesByDepartmentRequest) (*CountEmployeesByDepartmentResponse, error)
	CountEmployeesByClinic(context.Context, *CountEmployeesByClinicRequest) (*CountEmployeesByClinicResponse, error)
	CountEmployeesByOrganization(context.Context, *CountEmployeesByOrganizationRequest) (*CountEmployeesByOrganizationResponse, error)
	SearchEmployeesByOrganization(context.Context, *SearchEmployeesByOrganizationRequest) (*SearchEmployeesByOrganizationResponse, error)
	ListVacationsByEmployee(context.Context, *ListVacationsByEmployeeRequest) (*ListVacationsByEmployeeResponse, error)
	CountVacationsByEmployee(context.Context, *CountVacationsByEmployeeRequest) (*CountVacationsByEmployeeResponse, error)
	GetClinicHead(context.Context, *GetClinicHeadRequest) (*GetClinicHeadResponse, error)
	GetDepartmentResponsible(context.Context, *GetDepartmentResponsibleRequest) (*GetDepartmentResponsibleResponse, error)
	ListOrgAdmins(context.Context, *ListOrgAdminsRequest) (*ListOrgAdminsResponse, error)
	ListOrgDispatchers(context.Context, *ListOrgDispatchersRequest) (*ListOrgDispatchersResponse, error)
	ListOrgHeads(context.Context, *ListOrgHeadsRequest) (*ListOrgHeadsResponse, error)
	ListSystemAdmins(context.Context, *ListSystemAdminsRequest) (*ListSystemAdminsResponse, error)
	mustEmbedUnimplementedMembershipQueryServiceServer()
}

// UnimplementedMembershipQueryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMembershipQueryServiceServer struct{}

func (UnimplementedMembershipQueryServiceServer) GetEmployee(context.Context, *GetEmployeeRequest) (*GetEmployeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmployee not implemented")
}
func (UnimplementedMembershipQueryServiceServer) ListEmployeesByDepartment(context.Context, *ListEmployeesByDepartmentRequest) (*ListEmployeesByDepartmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEmployeesByDepartment not implemented")
}
func (UnimplementedMembershipQueryServiceServer) ListEmployeesByClinic(context.Context, *ListEmployeesByClinicRequest) (*ListEmployeesByClinicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEmployeesByClinic not implemented")
}
func (UnimplementedMembershipQueryServiceServer) ListEmployeesByOrganization(context.Context, *ListEmployeesByOrganizationRequest) (*ListEmployeesByOrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEmployeesByOrganization not implemented")
}
func (UnimplementedMembershipQueryServiceServer) CountEmployeesByDepartment(context.Context, *CountEmployeesByDepartmentRequest) (*CountEmployeesByDepartmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountEmployeesByDepartment not implemented")
}
func (UnimplementedMembershipQueryServiceServer) CountEmployeesByClinic(context.Context, *CountEmployeesByClinicRequest) (*CountEmployeesByClinicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountEmployeesByClinic not implemented")
}
func (UnimplementedMembershipQueryServiceServer) CountEmployeesByOrganization(context.Context, *CountEmployeesByOrganizationRequest) (*CountEmployeesByOrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountEmployeesByOrganization not implemented")
}
func (UnimplementedMembershipQueryServiceServer) SearchEmployeesByOrganization(context.Context, *SearchEmployeesByOrganizationRequest) (*SearchEmployeesByOrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchEmployeesByOrganization not implemented")
}
func (UnimplementedMembershipQueryServiceServer) ListVacationsByEmployee(context.Context, *ListVacationsByEmployeeRequest) (*ListVacationsByEmployeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListVacationsByEmployee not implemented")
}
func (UnimplementedMembershipQueryServiceServer) CountVacationsByEmployee(context.Context, *CountVacationsByEmployeeRequest) (*CountVacationsByEmployeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountVacationsByEmployee not implemented")
}
func (UnimplementedMembershipQueryServiceServer) GetClinicHead(context.Context, *GetClinicHeadRequest) (*GetClinicHeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClinicHead not implemented")
}
func (UnimplementedMembershipQueryServiceServer) GetDepartmentResponsible(context.Context, *GetDepartmentResponsibleRequest) (*GetDepartmentResponsibleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDepartmentResponsible not implemented")
}
func (UnimplementedMembershipQueryServiceServer) ListOrgAdmins(context.Context, *ListOrgAdminsRequest) (*ListOrgAdminsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrgAdmins not implemented")
}
func (UnimplementedMembershipQueryServiceServer) ListOrgDispatchers(context.Context, *ListOrgDispatchersRequest) (*ListOrgDispatchersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrgDispatchers not implemented")
}
func (UnimplementedMembershipQueryServiceServer) ListOrgHeads(context.Context, *ListOrgHeadsRequest) (*ListOrgHeadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrgHeads not implemented")
}
func (UnimplementedMembershipQueryServiceServer) ListSystemAdmins(context.Context, *ListSystemAdminsRequest) (*ListSystemAdminsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSystemAdmins not implemented")
}
func (UnimplementedMembershipQueryServiceServer) mustEmbedUnimplementedMembershipQueryServiceServer() {
}
func (UnimplementedMembershipQueryServiceServer) testEmbeddedByValue() {}

// UnsafeMembershipQueryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipQueryServiceServer will
// result in compilation errors.
type UnsafeMembershipQueryServiceServer interface {
	mustEmbedUnimplementedMembershipQueryServiceServer()
}

func RegisterMembershipQueryServiceServer(s grpc.ServiceRegistrar, srv MembershipQueryServiceServer) {
	// If the following call panics, it indicates UnimplementedMembershipQueryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MembershipQueryService_ServiceDesc, srv)
}

func _MembershipQueryService_GetEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).GetEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_GetEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).GetEmployee(ctx, req.(*GetEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_ListEmployeesByDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEmployeesByDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).ListEmployeesByDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_ListEmployeesByDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).ListEmployeesByDepartment(ctx, req.(*ListEmployeesByDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_ListEmployeesByClinic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEmployeesByClinicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).ListEmployeesByClinic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_ListEmployeesByClinic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).ListEmployeesByClinic(ctx, req.(*ListEmployeesByClinicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_ListEmployeesByOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEmployeesByOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).ListEmployeesByOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_ListEmployeesByOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).ListEmployeesByOrganization(ctx, req.(*ListEmployeesByOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_CountEmployeesByDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountEmployeesByDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).CountEmployeesByDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_CountEmployeesByDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).CountEmployeesByDepartment(ctx, req.(*CountEmployeesByDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_CountEmployeesByClinic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountEmployeesByClinicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).CountEmployeesByClinic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_CountEmployeesByClinic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).CountEmployeesByClinic(ctx, req.(*CountEmployeesByClinicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_CountEmployeesByOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountEmployeesByOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).CountEmployeesByOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_CountEmployeesByOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).CountEmployeesByOrganization(ctx, req.(*CountEmployeesByOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_SearchEmployeesByOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchEmployeesByOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).SearchEmployeesByOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_SearchEmployeesByOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).SearchEmployeesByOrganization(ctx, req.(*SearchEmployeesByOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_ListVacationsByEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVacationsByEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).ListVacationsByEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_ListVacationsByEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).ListVacationsByEmployee(ctx, req.(*ListVacationsByEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_CountVacationsByEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountVacationsByEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).CountVacationsByEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_CountVacationsByEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).CountVacationsByEmployee(ctx, req.(*CountVacationsByEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_GetClinicHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClinicHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).GetClinicHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_GetClinicHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).GetClinicHead(ctx, req.(*GetClinicHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_GetDepartmentResponsible_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDepartmentResponsibleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).GetDepartmentResponsible(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_GetDepartmentResponsible_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).GetDepartmentResponsible(ctx, req.(*GetDepartmentResponsibleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_ListOrgAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrgAdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).ListOrgAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_ListOrgAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).ListOrgAdmins(ctx, req.(*ListOrgAdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_ListOrgDispatchers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrgDispatchersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).ListOrgDispatchers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_ListOrgDispatchers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).ListOrgDispatchers(ctx, req.(*ListOrgDispatchersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_ListOrgHeads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrgHeadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).ListOrgHeads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_ListOrgHeads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).ListOrgHeads(ctx, req.(*ListOrgHeadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipQueryService_ListSystemAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSystemAdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipQueryServiceServer).ListSystemAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipQueryService_ListSystemAdmins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipQueryServiceServer).ListSystemAdmins(ctx, req.(*ListSystemAdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MembershipQueryService_ServiceDesc is the grpc.ServiceDesc for MembershipQueryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MembershipQueryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "query.membership.v1.MembershipQueryService",
	HandlerType: (*MembershipQueryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEmployee",
			Handler:    _MembershipQueryService_GetEmployee_Handler,
		},
		{
			MethodName: "ListEmployeesByDepartment",
			Handler:    _MembershipQueryService_ListEmployeesByDepartment_Handler,
		},
		{
			MethodName: "ListEmployeesByClinic",
			Handler:    _MembershipQueryService_ListEmployeesByClinic_Handler,
		},
		{
			MethodName: "ListEmployeesByOrganization",
			Handler:    _MembershipQueryService_ListEmployeesByOrganization_Handler,
		},
		{
			MethodName: "CountEmployeesByDepartment",
			Handler:    _MembershipQueryService_CountEmployeesByDepartment_Handler,
		},
		{
			MethodName: "CountEmployeesByClinic",
			Handler:    _MembershipQueryService_CountEmployeesByClinic_Handler,
		},
		{
			MethodName: "CountEmployeesByOrganization",
			Handler:    _MembershipQueryService_CountEmployeesByOrganization_Handler,
		},
		{
			MethodName: "SearchEmployeesByOrganization",
			Handler:    _MembershipQueryService_SearchEmployeesByOrganization_Handler,
		},
		{
			MethodName: "ListVacationsByEmployee",
			Handler:    _MembershipQueryService_ListVacationsByEmployee_Handler,
		},
		{
			MethodName: "CountVacationsByEmployee",
			Handler:    _MembershipQueryService_CountVacationsByEmployee_Handler,
		},
		{
			MethodName: "GetClinicHead",
			Handler:    _MembershipQueryService_GetClinicHead_Handler,
		},
		{
			MethodName: "GetDepartmentResponsible",
			Handler:    _MembershipQueryService_GetDepartmentResponsible_Handler,
		},
		{
			MethodName: "ListOrgAdmins",
			Handler:    _MembershipQueryService_ListOrgAdmins_Handler,
		},
		{
			MethodName: "ListOrgDispatchers",
			Handler:    _MembershipQueryService_ListOrgDispatchers_Handler,
		},
		{
			MethodName: "ListOrgHeads",
			Handler:    _MembershipQueryService_ListOrgHeads_Handler,
		},
		{
			MethodName: "ListSystemAdmins",
			Handler:    _MembershipQueryService_ListSystemAdmins_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "query/membership/v1/membership.proto",
}
