// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: event/organization/v1/events.proto

package organizationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Address is embedded in organization events that carry a legal address.
// Duplicated per-aggregate so aggregates can evolve independently.
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Point         *Point                 `protobuf:"bytes,2,opt,name=point,proto3" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_event_organization_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_event_organization_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_event_organization_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Address) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_event_organization_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_event_organization_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_event_organization_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Point) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

// OrganizationCreated is emitted when a new organization is persisted.
// subject: medincident.event.organization.v1.created
type OrganizationCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // empty = absent
	LegalAddress  *Address               `protobuf:"bytes,3,opt,name=legal_address,json=legalAddress,proto3" json:"legal_address,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationCreated) Reset() {
	*x = OrganizationCreated{}
	mi := &file_event_organization_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationCreated) ProtoMessage() {}

func (x *OrganizationCreated) ProtoReflect() protoreflect.Message {
	mi := &file_event_organization_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationCreated.ProtoReflect.Descriptor instead.
func (*OrganizationCreated) Descriptor() ([]byte, []int) {
	return file_event_organization_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *OrganizationCreated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationCreated) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrganizationCreated) GetLegalAddress() *Address {
	if x != nil {
		return x.LegalAddress
	}
	return nil
}

func (x *OrganizationCreated) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// OrganizationDetailsChanged is emitted when name or description changes.
// subject: medincident.event.organization.v1.details_changed
type OrganizationDetailsChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // empty = absent
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationDetailsChanged) Reset() {
	*x = OrganizationDetailsChanged{}
	mi := &file_event_organization_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationDetailsChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationDetailsChanged) ProtoMessage() {}

func (x *OrganizationDetailsChanged) ProtoReflect() protoreflect.Message {
	mi := &file_event_organization_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationDetailsChanged.ProtoReflect.Descriptor instead.
func (*OrganizationDetailsChanged) Descriptor() ([]byte, []int) {
	return file_event_organization_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *OrganizationDetailsChanged) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrganizationDetailsChanged) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OrganizationDetailsChanged) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// OrganizationLegalAddressChanged is emitted when the legal address changes.
// subject: medincident.event.organization.v1.legal_address_changed
type OrganizationLegalAddressChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LegalAddress  *Address               `protobuf:"bytes,1,opt,name=legal_address,json=legalAddress,proto3" json:"legal_address,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrganizationLegalAddressChanged) Reset() {
	*x = OrganizationLegalAddressChanged{}
	mi := &file_event_organization_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationLegalAddressChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationLegalAddressChanged) ProtoMessage() {}

func (x *OrganizationLegalAddressChanged) ProtoReflect() protoreflect.Message {
	mi := &file_event_organization_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrganizationLegalAddressChanged.ProtoReflect.Descriptor instead.
func (*OrganizationLegalAddressChanged) Descriptor() ([]byte, []int) {
	return file_event_organization_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *OrganizationLegalAddressChanged) GetLegalAddress() *Address {
	if x != nil {
		return x.LegalAddress
	}
	return nil
}

func (x *OrganizationLegalAddressChanged) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_event_organization_v1_events_proto protoreflect.FileDescriptor

const file_event_organization_v1_events_proto_rawDesc = "" +
	"\n" +
	"\"event/organization/v1/events.proto\x12\x15event.organization.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Q\n" +
	"\aAddress\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x122\n" +
	"\x05point\x18\x02 \x01(\v2\x1c.event.organization.v1.PointR\x05point\"A\n" +
	"\x05Point\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\"\xcb\x01\n" +
	"\x13OrganizationCreated\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12C\n" +
	"\rlegal_address\x18\x03 \x01(\v2\x1e.event.organization.v1.AddressR\flegalAddress\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8d\x01\n" +
	"\x1aOrganizationDetailsChanged\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa1\x01\n" +
	"\x1fOrganizationLegalAddressChanged\x12C\n" +
	"\rlegal_address\x18\x01 \x01(\v2\x1e.event.organization.v1.AddressR\flegalAddress\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\xf3\x01\n" +
	"\x19com.event.organization.v1B\vEventsProtoP\x01ZSgithub.com/medincident/medincident-backend/pkg/event/organization/v1;organizationv1\xa2\x02\x03EOX\xaa\x02\x15Event.Organization.V1\xca\x02\x15Event\\Organization\\V1\xe2\x02!Event\\Organization\\V1\\GPBMetadata\xea\x02\x17Event::Organization::V1b\x06proto3"

var (
	file_event_organization_v1_events_proto_rawDescOnce sync.Once
	file_event_organization_v1_events_proto_rawDescData []byte
)

func file_event_organization_v1_events_proto_rawDescGZIP() []byte {
	file_event_organization_v1_events_proto_rawDescOnce.Do(func() {
		file_event_organization_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_organization_v1_events_proto_rawDesc), len(file_event_organization_v1_events_proto_rawDesc)))
	})
	return file_event_organization_v1_events_proto_rawDescData
}

var file_event_organization_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_event_organization_v1_events_proto_goTypes = []any{
	(*Address)(nil),                         // 0: event.organization.v1.Address
	(*Point)(nil),                           // 1: event.organization.v1.Point
	(*OrganizationCreated)(nil),             // 2: event.organization.v1.OrganizationCreated
	(*OrganizationDetailsChanged)(nil),      // 3: event.organization.v1.OrganizationDetailsChanged
	(*OrganizationLegalAddressChanged)(nil), // 4: event.organization.v1.OrganizationLegalAddressChanged
	(*timestamppb.Timestamp)(nil),           // 5: google.protobuf.Timestamp
}
var file_event_organization_v1_events_proto_depIdxs = []int32{
	1, // 0: event.organization.v1.Address.point:type_name -> event.organization.v1.Point
	0, // 1: event.organization.v1.OrganizationCreated.legal_address:type_name -> event.organization.v1.Address
	5, // 2: event.organization.v1.OrganizationCreated.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: event.organization.v1.OrganizationDetailsChanged.updated_at:type_name -> google.protobuf.Timestamp
	0, // 4: event.organization.v1.OrganizationLegalAddressChanged.legal_address:type_name -> event.organization.v1.Address
	5, // 5: event.organization.v1.OrganizationLegalAddressChanged.updated_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_event_organization_v1_events_proto_init() }
func file_event_organization_v1_events_proto_init() {
	if File_event_organization_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_organization_v1_events_proto_rawDesc), len(file_event_organization_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_organization_v1_events_proto_goTypes,
		DependencyIndexes: file_event_organization_v1_events_proto_depIdxs,
		MessageInfos:      file_event_organization_v1_events_proto_msgTypes,
	}.Build()
	File_event_organization_v1_events_proto = out.File
	file_event_organization_v1_events_proto_goTypes = nil
	file_event_organization_v1_events_proto_depIdxs = nil
}
