// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: command/orgstructure/v1/orgstructure.proto

package orgstructurev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrgStructureCommandService_CreateOrganization_FullMethodName             = "/command.orgstructure.v1.OrgStructureCommandService/CreateOrganization"
	OrgStructureCommandService_UpdateOrganizationDetails_FullMethodName      = "/command.orgstructure.v1.OrgStructureCommandService/UpdateOrganizationDetails"
	OrgStructureCommandService_UpdateOrganizationLegalAddress_FullMethodName = "/command.orgstructure.v1.OrgStructureCommandService/UpdateOrganizationLegalAddress"
	OrgStructureCommandService_DeactivateOrganization_FullMethodName         = "/command.orgstructure.v1.OrgStructureCommandService/DeactivateOrganization"
	OrgStructureCommandService_ActivateOrganization_FullMethodName           = "/command.orgstructure.v1.OrgStructureCommandService/ActivateOrganization"
	OrgStructureCommandService_DeleteOrganization_FullMethodName             = "/command.orgstructure.v1.OrgStructureCommandService/DeleteOrganization"
	OrgStructureCommandService_CreateClinic_FullMethodName                   = "/command.orgstructure.v1.OrgStructureCommandService/CreateClinic"
	OrgStructureCommandService_UpdateClinicDetails_FullMethodName            = "/command.orgstructure.v1.OrgStructureCommandService/UpdateClinicDetails"
	OrgStructureCommandService_UpdateClinicPhysicalAddress_FullMethodName    = "/command.orgstructure.v1.OrgStructureCommandService/UpdateClinicPhysicalAddress"
	OrgStructureCommandService_DeactivateClinic_FullMethodName               = "/command.orgstructure.v1.OrgStructureCommandService/DeactivateClinic"
	OrgStructureCommandService_ActivateClinic_FullMethodName                 = "/command.orgstructure.v1.OrgStructureCommandService/ActivateClinic"
	OrgStructureCommandService_DeleteClinic_FullMethodName                   = "/command.orgstructure.v1.OrgStructureCommandService/DeleteClinic"
	OrgStructureCommandService_CreateDepartment_FullMethodName               = "/command.orgstructure.v1.OrgStructureCommandService/CreateDepartment"
	OrgStructureCommandService_UpdateDepartmentDetails_FullMethodName        = "/command.orgstructure.v1.OrgStructureCommandService/UpdateDepartmentDetails"
	OrgStructureCommandService_DeactivateDepartment_FullMethodName           = "/command.orgstructure.v1.OrgStructureCommandService/DeactivateDepartment"
	OrgStructureCommandService_ActivateDepartment_FullMethodName             = "/command.orgstructure.v1.OrgStructureCommandService/ActivateDepartment"
	OrgStructureCommandService_DeleteDepartment_FullMethodName               = "/command.orgstructure.v1.OrgStructureCommandService/DeleteDepartment"
)

// OrgStructureCommandServiceClient is the client API for OrgStructureCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrgStructureCommandService is the command-side contract for the three
// organisational structure aggregates: Organization, Clinic, and
// Department. Every mutation returns either an identifier (Create) or
// an empty response (Update). google.api.http annotations drive the
// gateway-server binary in this repo (cmd/gateway-server): the
// command-server itself serves pure gRPC, and gateway-server dials
// into it and exposes a REST facade using the grpc-gateway stubs
// generated under pkg/.
type OrgStructureCommandServiceClient interface {
	CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*CreateOrganizationResponse, error)
	UpdateOrganizationDetails(ctx context.Context, in *UpdateOrganizationDetailsRequest, opts ...grpc.CallOption) (*UpdateOrganizationDetailsResponse, error)
	UpdateOrganizationLegalAddress(ctx context.Context, in *UpdateOrganizationLegalAddressRequest, opts ...grpc.CallOption) (*UpdateOrganizationLegalAddressResponse, error)
	DeactivateOrganization(ctx context.Context, in *DeactivateOrganizationRequest, opts ...grpc.CallOption) (*DeactivateOrganizationResponse, error)
	ActivateOrganization(ctx context.Context, in *ActivateOrganizationRequest, opts ...grpc.CallOption) (*ActivateOrganizationResponse, error)
	DeleteOrganization(ctx context.Context, in *DeleteOrganizationRequest, opts ...grpc.CallOption) (*DeleteOrganizationResponse, error)
	CreateClinic(ctx context.Context, in *CreateClinicRequest, opts ...grpc.CallOption) (*CreateClinicResponse, error)
	UpdateClinicDetails(ctx context.Context, in *UpdateClinicDetailsRequest, opts ...grpc.CallOption) (*UpdateClinicDetailsResponse, error)
	UpdateClinicPhysicalAddress(ctx context.Context, in *UpdateClinicPhysicalAddressRequest, opts ...grpc.CallOption) (*UpdateClinicPhysicalAddressResponse, error)
	DeactivateClinic(ctx context.Context, in *DeactivateClinicRequest, opts ...grpc.CallOption) (*DeactivateClinicResponse, error)
	ActivateClinic(ctx context.Context, in *ActivateClinicRequest, opts ...grpc.CallOption) (*ActivateClinicResponse, error)
	DeleteClinic(ctx context.Context, in *DeleteClinicRequest, opts ...grpc.CallOption) (*DeleteClinicResponse, error)
	CreateDepartment(ctx context.Context, in *CreateDepartmentRequest, opts ...grpc.CallOption) (*CreateDepartmentResponse, error)
	UpdateDepartmentDetails(ctx context.Context, in *UpdateDepartmentDetailsRequest, opts ...grpc.CallOption) (*UpdateDepartmentDetailsResponse, error)
	DeactivateDepartment(ctx context.Context, in *DeactivateDepartmentRequest, opts ...grpc.CallOption) (*DeactivateDepartmentResponse, error)
	ActivateDepartment(ctx context.Context, in *ActivateDepartmentRequest, opts ...grpc.CallOption) (*ActivateDepartmentResponse, error)
	DeleteDepartment(ctx context.Context, in *DeleteDepartmentRequest, opts ...grpc.CallOption) (*DeleteDepartmentResponse, error)
}

type orgStructureCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrgStructureCommandServiceClient(cc grpc.ClientConnInterface) OrgStructureCommandServiceClient {
	return &orgStructureCommandServiceClient{cc}
}

func (c *orgStructureCommandServiceClient) CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*CreateOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrganizationResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_CreateOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) UpdateOrganizationDetails(ctx context.Context, in *UpdateOrganizationDetailsRequest, opts ...grpc.CallOption) (*UpdateOrganizationDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrganizationDetailsResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_UpdateOrganizationDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) UpdateOrganizationLegalAddress(ctx context.Context, in *UpdateOrganizationLegalAddressRequest, opts ...grpc.CallOption) (*UpdateOrganizationLegalAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateOrganizationLegalAddressResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_UpdateOrganizationLegalAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) DeactivateOrganization(ctx context.Context, in *DeactivateOrganizationRequest, opts ...grpc.CallOption) (*DeactivateOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateOrganizationResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_DeactivateOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) ActivateOrganization(ctx context.Context, in *ActivateOrganizationRequest, opts ...grpc.CallOption) (*ActivateOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateOrganizationResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_ActivateOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) DeleteOrganization(ctx context.Context, in *DeleteOrganizationRequest, opts ...grpc.CallOption) (*DeleteOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOrganizationResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_DeleteOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) CreateClinic(ctx context.Context, in *CreateClinicRequest, opts ...grpc.CallOption) (*CreateClinicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateClinicResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_CreateClinic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) UpdateClinicDetails(ctx context.Context, in *UpdateClinicDetailsRequest, opts ...grpc.CallOption) (*UpdateClinicDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateClinicDetailsResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_UpdateClinicDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) UpdateClinicPhysicalAddress(ctx context.Context, in *UpdateClinicPhysicalAddressRequest, opts ...grpc.CallOption) (*UpdateClinicPhysicalAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateClinicPhysicalAddressResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_UpdateClinicPhysicalAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) DeactivateClinic(ctx context.Context, in *DeactivateClinicRequest, opts ...grpc.CallOption) (*DeactivateClinicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateClinicResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_DeactivateClinic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) ActivateClinic(ctx context.Context, in *ActivateClinicRequest, opts ...grpc.CallOption) (*ActivateClinicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateClinicResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_ActivateClinic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) DeleteClinic(ctx context.Context, in *DeleteClinicRequest, opts ...grpc.CallOption) (*DeleteClinicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteClinicResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_DeleteClinic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) CreateDepartment(ctx context.Context, in *CreateDepartmentRequest, opts ...grpc.CallOption) (*CreateDepartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDepartmentResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_CreateDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) UpdateDepartmentDetails(ctx context.Context, in *UpdateDepartmentDetailsRequest, opts ...grpc.CallOption) (*UpdateDepartmentDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDepartmentDetailsResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_UpdateDepartmentDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) DeactivateDepartment(ctx context.Context, in *DeactivateDepartmentRequest, opts ...grpc.CallOption) (*DeactivateDepartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateDepartmentResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_DeactivateDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) ActivateDepartment(ctx context.Context, in *ActivateDepartmentRequest, opts ...grpc.CallOption) (*ActivateDepartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateDepartmentResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_ActivateDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgStructureCommandServiceClient) DeleteDepartment(ctx context.Context, in *DeleteDepartmentRequest, opts ...grpc.CallOption) (*DeleteDepartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDepartmentResponse)
	err := c.cc.Invoke(ctx, OrgStructureCommandService_DeleteDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrgStructureCommandServiceServer is the server API for OrgStructureCommandService service.
// All implementations must embed UnimplementedOrgStructureCommandServiceServer
// for forward compatibility.
//
// OrgStructureCommandService is the command-side contract for the three
// organisational structure aggregates: Organization, Clinic, and
// Department. Every mutation returns either an identifier (Create) or
// an empty response (Update). google.api.http annotations drive the
// gateway-server binary in this repo (cmd/gateway-server): the
// command-server itself serves pure gRPC, and gateway-server dials
// into it and exposes a REST facade using the grpc-gateway stubs
// generated under pkg/.
type OrgStructureCommandServiceServer interface {
	CreateOrganization(context.Context, *CreateOrganizationRequest) (*CreateOrganizationResponse, error)
	UpdateOrganizationDetails(context.Context, *UpdateOrganizationDetailsRequest) (*UpdateOrganizationDetailsResponse, error)
	UpdateOrganizationLegalAddress(context.Context, *UpdateOrganizationLegalAddressRequest) (*UpdateOrganizationLegalAddressResponse, error)
	DeactivateOrganization(context.Context, *DeactivateOrganizationRequest) (*DeactivateOrganizationResponse, error)
	ActivateOrganization(context.Context, *ActivateOrganizationRequest) (*ActivateOrganizationResponse, error)
	DeleteOrganization(context.Context, *DeleteOrganizationRequest) (*DeleteOrganizationResponse, error)
	CreateClinic(context.Context, *CreateClinicRequest) (*CreateClinicResponse, error)
	UpdateClinicDetails(context.Context, *UpdateClinicDetailsRequest) (*UpdateClinicDetailsResponse, error)
	UpdateClinicPhysicalAddress(context.Context, *UpdateClinicPhysicalAddressRequest) (*UpdateClinicPhysicalAddressResponse, error)
	DeactivateClinic(context.Context, *DeactivateClinicRequest) (*DeactivateClinicResponse, error)
	ActivateClinic(context.Context, *ActivateClinicRequest) (*ActivateClinicResponse, error)
	DeleteClinic(context.Context, *DeleteClinicRequest) (*DeleteClinicResponse, error)
	CreateDepartment(context.Context, *CreateDepartmentRequest) (*CreateDepartmentResponse, error)
	UpdateDepartmentDetails(context.Context, *UpdateDepartmentDetailsRequest) (*UpdateDepartmentDetailsResponse, error)
	DeactivateDepartment(context.Context, *DeactivateDepartmentRequest) (*DeactivateDepartmentResponse, error)
	ActivateDepartment(context.Context, *ActivateDepartmentRequest) (*ActivateDepartmentResponse, error)
	DeleteDepartment(context.Context, *DeleteDepartmentRequest) (*DeleteDepartmentResponse, error)
	mustEmbedUnimplementedOrgStructureCommandServiceServer()
}

// UnimplementedOrgStructureCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrgStructureCommandServiceServer struct{}

func (UnimplementedOrgStructureCommandServiceServer) CreateOrganization(context.Context, *CreateOrganizationRequest) (*CreateOrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrganization not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) UpdateOrganizationDetails(context.Context, *UpdateOrganizationDetailsRequest) (*UpdateOrganizationDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrganizationDetails not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) UpdateOrganizationLegalAddress(context.Context, *UpdateOrganizationLegalAddressRequest) (*UpdateOrganizationLegalAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrganizationLegalAddress not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) DeactivateOrganization(context.Context, *DeactivateOrganizationRequest) (*DeactivateOrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateOrganization not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) ActivateOrganization(context.Context, *ActivateOrganizationRequest) (*ActivateOrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateOrganization not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) DeleteOrganization(context.Context, *DeleteOrganizationRequest) (*DeleteOrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOrganization not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) CreateClinic(context.Context, *CreateClinicRequest) (*CreateClinicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateClinic not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) UpdateClinicDetails(context.Context, *UpdateClinicDetailsRequest) (*UpdateClinicDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateClinicDetails not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) UpdateClinicPhysicalAddress(context.Context, *UpdateClinicPhysicalAddressRequest) (*UpdateClinicPhysicalAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateClinicPhysicalAddress not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) DeactivateClinic(context.Context, *DeactivateClinicRequest) (*DeactivateClinicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateClinic not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) ActivateClinic(context.Context, *ActivateClinicRequest) (*ActivateClinicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateClinic not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) DeleteClinic(context.Context, *DeleteClinicRequest) (*DeleteClinicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteClinic not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) CreateDepartment(context.Context, *CreateDepartmentRequest) (*CreateDepartmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDepartment not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) UpdateDepartmentDetails(context.Context, *UpdateDepartmentDetailsRequest) (*UpdateDepartmentDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDepartmentDetails not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) DeactivateDepartment(context.Context, *DeactivateDepartmentRequest) (*DeactivateDepartmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateDepartment not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) ActivateDepartment(context.Context, *ActivateDepartmentRequest) (*ActivateDepartmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateDepartment not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) DeleteDepartment(context.Context, *DeleteDepartmentRequest) (*DeleteDepartmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDepartment not implemented")
}
func (UnimplementedOrgStructureCommandServiceServer) mustEmbedUnimplementedOrgStructureCommandServiceServer() {
}
func (UnimplementedOrgStructureCommandServiceServer) testEmbeddedByValue() {}

// UnsafeOrgStructureCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrgStructureCommandServiceServer will
// result in compilation errors.
type UnsafeOrgStructureCommandServiceServer interface {
	mustEmbedUnimplementedOrgStructureCommandServiceServer()
}

func RegisterOrgStructureCommandServiceServer(s grpc.ServiceRegistrar, srv OrgStructureCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedOrgStructureCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrgStructureCommandService_ServiceDesc, srv)
}

func _OrgStructureCommandService_CreateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).CreateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_CreateOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).CreateOrganization(ctx, req.(*CreateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_UpdateOrganizationDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrganizationDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).UpdateOrganizationDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_UpdateOrganizationDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).UpdateOrganizationDetails(ctx, req.(*UpdateOrganizationDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_UpdateOrganizationLegalAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrganizationLegalAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).UpdateOrganizationLegalAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_UpdateOrganizationLegalAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).UpdateOrganizationLegalAddress(ctx, req.(*UpdateOrganizationLegalAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_DeactivateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).DeactivateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_DeactivateOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).DeactivateOrganization(ctx, req.(*DeactivateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_ActivateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).ActivateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_ActivateOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).ActivateOrganization(ctx, req.(*ActivateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_DeleteOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).DeleteOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_DeleteOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).DeleteOrganization(ctx, req.(*DeleteOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_CreateClinic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateClinicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).CreateClinic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_CreateClinic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).CreateClinic(ctx, req.(*CreateClinicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_UpdateClinicDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClinicDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).UpdateClinicDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_UpdateClinicDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).UpdateClinicDetails(ctx, req.(*UpdateClinicDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_UpdateClinicPhysicalAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateClinicPhysicalAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).UpdateClinicPhysicalAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_UpdateClinicPhysicalAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).UpdateClinicPhysicalAddress(ctx, req.(*UpdateClinicPhysicalAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_DeactivateClinic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateClinicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).DeactivateClinic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_DeactivateClinic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).DeactivateClinic(ctx, req.(*DeactivateClinicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_ActivateClinic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateClinicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).ActivateClinic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_ActivateClinic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).ActivateClinic(ctx, req.(*ActivateClinicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_DeleteClinic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteClinicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).DeleteClinic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_DeleteClinic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).DeleteClinic(ctx, req.(*DeleteClinicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_CreateDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).CreateDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_CreateDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).CreateDepartment(ctx, req.(*CreateDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_UpdateDepartmentDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDepartmentDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).UpdateDepartmentDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_UpdateDepartmentDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).UpdateDepartmentDetails(ctx, req.(*UpdateDepartmentDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_DeactivateDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).DeactivateDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_DeactivateDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).DeactivateDepartment(ctx, req.(*DeactivateDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_ActivateDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).ActivateDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_ActivateDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).ActivateDepartment(ctx, req.(*ActivateDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrgStructureCommandService_DeleteDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgStructureCommandServiceServer).DeleteDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgStructureCommandService_DeleteDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgStructureCommandServiceServer).DeleteDepartment(ctx, req.(*DeleteDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrgStructureCommandService_ServiceDesc is the grpc.ServiceDesc for OrgStructureCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrgStructureCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "command.orgstructure.v1.OrgStructureCommandService",
	HandlerType: (*OrgStructureCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrganization",
			Handler:    _OrgStructureCommandService_CreateOrganization_Handler,
		},
		{
			MethodName: "UpdateOrganizationDetails",
			Handler:    _OrgStructureCommandService_UpdateOrganizationDetails_Handler,
		},
		{
			MethodName: "UpdateOrganizationLegalAddress",
			Handler:    _OrgStructureCommandService_UpdateOrganizationLegalAddress_Handler,
		},
		{
			MethodName: "DeactivateOrganization",
			Handler:    _OrgStructureCommandService_DeactivateOrganization_Handler,
		},
		{
			MethodName: "ActivateOrganization",
			Handler:    _OrgStructureCommandService_ActivateOrganization_Handler,
		},
		{
			MethodName: "DeleteOrganization",
			Handler:    _OrgStructureCommandService_DeleteOrganization_Handler,
		},
		{
			MethodName: "CreateClinic",
			Handler:    _OrgStructureCommandService_CreateClinic_Handler,
		},
		{
			MethodName: "UpdateClinicDetails",
			Handler:    _OrgStructureCommandService_UpdateClinicDetails_Handler,
		},
		{
			MethodName: "UpdateClinicPhysicalAddress",
			Handler:    _OrgStructureCommandService_UpdateClinicPhysicalAddress_Handler,
		},
		{
			MethodName: "DeactivateClinic",
			Handler:    _OrgStructureCommandService_DeactivateClinic_Handler,
		},
		{
			MethodName: "ActivateClinic",
			Handler:    _OrgStructureCommandService_ActivateClinic_Handler,
		},
		{
			MethodName: "DeleteClinic",
			Handler:    _OrgStructureCommandService_DeleteClinic_Handler,
		},
		{
			MethodName: "CreateDepartment",
			Handler:    _OrgStructureCommandService_CreateDepartment_Handler,
		},
		{
			MethodName: "UpdateDepartmentDetails",
			Handler:    _OrgStructureCommandService_UpdateDepartmentDetails_Handler,
		},
		{
			MethodName: "DeactivateDepartment",
			Handler:    _OrgStructureCommandService_DeactivateDepartment_Handler,
		},
		{
			MethodName: "ActivateDepartment",
			Handler:    _OrgStructureCommandService_ActivateDepartment_Handler,
		},
		{
			MethodName: "DeleteDepartment",
			Handler:    _OrgStructureCommandService_DeleteDepartment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "command/orgstructure/v1/orgstructure.proto",
}
