// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: command/orgstructure/v1/orgstructure.proto

package orgstructurev1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/medincident/medincident-backend/pkg/error/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PointInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Longitude     float64                `protobuf:"fixed64,1,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PointInput) Reset() {
	*x = PointInput{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PointInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PointInput) ProtoMessage() {}

func (x *PointInput) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PointInput.ProtoReflect.Descriptor instead.
func (*PointInput) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{0}
}

func (x *PointInput) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PointInput) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type AddressInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Point         *PointInput            `protobuf:"bytes,2,opt,name=point,proto3,oneof" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressInput) Reset() {
	*x = AddressInput{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressInput) ProtoMessage() {}

func (x *AddressInput) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressInput.ProtoReflect.Descriptor instead.
func (*AddressInput) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{1}
}

func (x *AddressInput) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AddressInput) GetPoint() *PointInput {
	if x != nil {
		return x.Point
	}
	return nil
}

type CreateOrganizationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LegalAddress  *AddressInput          `protobuf:"bytes,2,opt,name=legal_address,json=legalAddress,proto3" json:"legal_address,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrganizationRequest) Reset() {
	*x = CreateOrganizationRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationRequest) ProtoMessage() {}

func (x *CreateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrganizationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrganizationRequest) GetLegalAddress() *AddressInput {
	if x != nil {
		return x.LegalAddress
	}
	return nil
}

func (x *CreateOrganizationRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateOrganizationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrganizationResponse) Reset() {
	*x = CreateOrganizationResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrganizationResponse) ProtoMessage() {}

func (x *CreateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*CreateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrganizationResponse) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type UpdateOrganizationDetailsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateOrganizationDetailsRequest) Reset() {
	*x = UpdateOrganizationDetailsRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationDetailsRequest) ProtoMessage() {}

func (x *UpdateOrganizationDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationDetailsRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOrganizationDetailsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateOrganizationDetailsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateOrganizationDetailsRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdateOrganizationDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationDetailsResponse) Reset() {
	*x = UpdateOrganizationDetailsResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationDetailsResponse) ProtoMessage() {}

func (x *UpdateOrganizationDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationDetailsResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationDetailsResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{5}
}

type UpdateOrganizationLegalAddressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	LegalAddress   *AddressInput          `protobuf:"bytes,2,opt,name=legal_address,json=legalAddress,proto3" json:"legal_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateOrganizationLegalAddressRequest) Reset() {
	*x = UpdateOrganizationLegalAddressRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationLegalAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationLegalAddressRequest) ProtoMessage() {}

func (x *UpdateOrganizationLegalAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationLegalAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationLegalAddressRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOrganizationLegalAddressRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *UpdateOrganizationLegalAddressRequest) GetLegalAddress() *AddressInput {
	if x != nil {
		return x.LegalAddress
	}
	return nil
}

type UpdateOrganizationLegalAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrganizationLegalAddressResponse) Reset() {
	*x = UpdateOrganizationLegalAddressResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrganizationLegalAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrganizationLegalAddressResponse) ProtoMessage() {}

func (x *UpdateOrganizationLegalAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrganizationLegalAddressResponse.ProtoReflect.Descriptor instead.
func (*UpdateOrganizationLegalAddressResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{7}
}

type DeactivateOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeactivateOrganizationRequest) Reset() {
	*x = DeactivateOrganizationRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateOrganizationRequest) ProtoMessage() {}

func (x *DeactivateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*DeactivateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{8}
}

func (x *DeactivateOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type DeactivateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateOrganizationResponse) Reset() {
	*x = DeactivateOrganizationResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateOrganizationResponse) ProtoMessage() {}

func (x *DeactivateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*DeactivateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{9}
}

type ActivateOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActivateOrganizationRequest) Reset() {
	*x = ActivateOrganizationRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateOrganizationRequest) ProtoMessage() {}

func (x *ActivateOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateOrganizationRequest.ProtoReflect.Descriptor instead.
func (*ActivateOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{10}
}

func (x *ActivateOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ActivateOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateOrganizationResponse) Reset() {
	*x = ActivateOrganizationResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateOrganizationResponse) ProtoMessage() {}

func (x *ActivateOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateOrganizationResponse.ProtoReflect.Descriptor instead.
func (*ActivateOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{11}
}

type DeleteOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteOrganizationRequest) Reset() {
	*x = DeleteOrganizationRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationRequest) ProtoMessage() {}

func (x *DeleteOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type DeleteOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrganizationResponse) Reset() {
	*x = DeleteOrganizationResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrganizationResponse) ProtoMessage() {}

func (x *DeleteOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrganizationResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{13}
}

type CreateClinicRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId  string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhysicalAddress *AddressInput          `protobuf:"bytes,3,opt,name=physical_address,json=physicalAddress,proto3" json:"physical_address,omitempty"`
	Description     *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateClinicRequest) Reset() {
	*x = CreateClinicRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClinicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClinicRequest) ProtoMessage() {}

func (x *CreateClinicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClinicRequest.ProtoReflect.Descriptor instead.
func (*CreateClinicRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{14}
}

func (x *CreateClinicRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateClinicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClinicRequest) GetPhysicalAddress() *AddressInput {
	if x != nil {
		return x.PhysicalAddress
	}
	return nil
}

func (x *CreateClinicRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateClinicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClinicId      string                 `protobuf:"bytes,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClinicResponse) Reset() {
	*x = CreateClinicResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClinicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClinicResponse) ProtoMessage() {}

func (x *CreateClinicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClinicResponse.ProtoReflect.Descriptor instead.
func (*CreateClinicResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{15}
}

func (x *CreateClinicResponse) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

type UpdateClinicDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClinicId      string                 `protobuf:"bytes,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClinicDetailsRequest) Reset() {
	*x = UpdateClinicDetailsRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClinicDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClinicDetailsRequest) ProtoMessage() {}

func (x *UpdateClinicDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClinicDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateClinicDetailsRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateClinicDetailsRequest) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *UpdateClinicDetailsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateClinicDetailsRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdateClinicDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClinicDetailsResponse) Reset() {
	*x = UpdateClinicDetailsResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClinicDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClinicDetailsResponse) ProtoMessage() {}

func (x *UpdateClinicDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClinicDetailsResponse.ProtoReflect.Descriptor instead.
func (*UpdateClinicDetailsResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{17}
}

type UpdateClinicPhysicalAddressRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClinicId        string                 `protobuf:"bytes,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	PhysicalAddress *AddressInput          `protobuf:"bytes,2,opt,name=physical_address,json=physicalAddress,proto3" json:"physical_address,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateClinicPhysicalAddressRequest) Reset() {
	*x = UpdateClinicPhysicalAddressRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClinicPhysicalAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClinicPhysicalAddressRequest) ProtoMessage() {}

func (x *UpdateClinicPhysicalAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClinicPhysicalAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateClinicPhysicalAddressRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateClinicPhysicalAddressRequest) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *UpdateClinicPhysicalAddressRequest) GetPhysicalAddress() *AddressInput {
	if x != nil {
		return x.PhysicalAddress
	}
	return nil
}

type UpdateClinicPhysicalAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClinicPhysicalAddressResponse) Reset() {
	*x = UpdateClinicPhysicalAddressResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClinicPhysicalAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClinicPhysicalAddressResponse) ProtoMessage() {}

func (x *UpdateClinicPhysicalAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClinicPhysicalAddressResponse.ProtoReflect.Descriptor instead.
func (*UpdateClinicPhysicalAddressResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{19}
}

type DeactivateClinicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClinicId      string                 `protobuf:"bytes,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateClinicRequest) Reset() {
	*x = DeactivateClinicRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateClinicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateClinicRequest) ProtoMessage() {}

func (x *DeactivateClinicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateClinicRequest.ProtoReflect.Descriptor instead.
func (*DeactivateClinicRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{20}
}

func (x *DeactivateClinicRequest) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

type DeactivateClinicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateClinicResponse) Reset() {
	*x = DeactivateClinicResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateClinicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateClinicResponse) ProtoMessage() {}

func (x *DeactivateClinicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateClinicResponse.ProtoReflect.Descriptor instead.
func (*DeactivateClinicResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{21}
}

type ActivateClinicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClinicId      string                 `protobuf:"bytes,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateClinicRequest) Reset() {
	*x = ActivateClinicRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateClinicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateClinicRequest) ProtoMessage() {}

func (x *ActivateClinicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateClinicRequest.ProtoReflect.Descriptor instead.
func (*ActivateClinicRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{22}
}

func (x *ActivateClinicRequest) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

type ActivateClinicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateClinicResponse) Reset() {
	*x = ActivateClinicResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateClinicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateClinicResponse) ProtoMessage() {}

func (x *ActivateClinicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateClinicResponse.ProtoReflect.Descriptor instead.
func (*ActivateClinicResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{23}
}

type DeleteClinicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClinicId      string                 `protobuf:"bytes,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClinicRequest) Reset() {
	*x = DeleteClinicRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClinicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClinicRequest) ProtoMessage() {}

func (x *DeleteClinicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClinicRequest.ProtoReflect.Descriptor instead.
func (*DeleteClinicRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteClinicRequest) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

type DeleteClinicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClinicResponse) Reset() {
	*x = DeleteClinicResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClinicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClinicResponse) ProtoMessage() {}

func (x *DeleteClinicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClinicResponse.ProtoReflect.Descriptor instead.
func (*DeleteClinicResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{25}
}

type CreateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClinicId      string                 `protobuf:"bytes,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentRequest) Reset() {
	*x = CreateDepartmentRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentRequest) ProtoMessage() {}

func (x *CreateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*CreateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{26}
}

func (x *CreateDepartmentRequest) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *CreateDepartmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDepartmentRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type CreateDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentResponse) Reset() {
	*x = CreateDepartmentResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentResponse) ProtoMessage() {}

func (x *CreateDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentResponse.ProtoReflect.Descriptor instead.
func (*CreateDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{27}
}

func (x *CreateDepartmentResponse) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type UpdateDepartmentDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDepartmentDetailsRequest) Reset() {
	*x = UpdateDepartmentDetailsRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepartmentDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentDetailsRequest) ProtoMessage() {}

func (x *UpdateDepartmentDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentDetailsRequest.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentDetailsRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateDepartmentDetailsRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *UpdateDepartmentDetailsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDepartmentDetailsRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type UpdateDepartmentDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDepartmentDetailsResponse) Reset() {
	*x = UpdateDepartmentDetailsResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepartmentDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentDetailsResponse) ProtoMessage() {}

func (x *UpdateDepartmentDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentDetailsResponse.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentDetailsResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{29}
}

type DeactivateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateDepartmentRequest) Reset() {
	*x = DeactivateDepartmentRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateDepartmentRequest) ProtoMessage() {}

func (x *DeactivateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*DeactivateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{30}
}

func (x *DeactivateDepartmentRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type DeactivateDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateDepartmentResponse) Reset() {
	*x = DeactivateDepartmentResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateDepartmentResponse) ProtoMessage() {}

func (x *DeactivateDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateDepartmentResponse.ProtoReflect.Descriptor instead.
func (*DeactivateDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{31}
}

type ActivateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateDepartmentRequest) Reset() {
	*x = ActivateDepartmentRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateDepartmentRequest) ProtoMessage() {}

func (x *ActivateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*ActivateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{32}
}

func (x *ActivateDepartmentRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type ActivateDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateDepartmentResponse) Reset() {
	*x = ActivateDepartmentResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateDepartmentResponse) ProtoMessage() {}

func (x *ActivateDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateDepartmentResponse.ProtoReflect.Descriptor instead.
func (*ActivateDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{33}
}

type DeleteDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentRequest) Reset() {
	*x = DeleteDepartmentRequest{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentRequest) ProtoMessage() {}

func (x *DeleteDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{34}
}

func (x *DeleteDepartmentRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type DeleteDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentResponse) Reset() {
	*x = DeleteDepartmentResponse{}
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentResponse) ProtoMessage() {}

func (x *DeleteDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_orgstructure_v1_orgstructure_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP(), []int{35}
}

var File_command_orgstructure_v1_orgstructure_proto protoreflect.FileDescriptor

const file_command_orgstructure_v1_orgstructure_proto_rawDesc = "" +
	"\n" +
	"*command/orgstructure/v1/orgstructure.proto\x12\x17command.orgstructure.v1\x1a\x14error/v1/error.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"F\n" +
	"\n" +
	"PointInput\x12\x1c\n" +
	"\tlongitude\x18\x01 \x01(\x01R\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\"q\n" +
	"\fAddressInput\x12\x17\n" +
	"\x04text\x18\x01 \x01(\tB\x03\xe0A\x02R\x04text\x12>\n" +
	"\x05point\x18\x02 \x01(\v2#.command.orgstructure.v1.PointInputH\x00R\x05point\x88\x01\x01B\b\n" +
	"\x06_point\"\xbc\x01\n" +
	"\x19CreateOrganizationRequest\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\x02R\x04name\x12O\n" +
	"\rlegal_address\x18\x02 \x01(\v2%.command.orgstructure.v1.AddressInputB\x03\xe0A\x02R\flegalAddress\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"E\n" +
	"\x1aCreateOrganizationResponse\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"\xa0\x01\n" +
	" UpdateOrganizationDetailsRequest\x12,\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x0eorganizationId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"#\n" +
	"!UpdateOrganizationDetailsResponse\"\xa6\x01\n" +
	"%UpdateOrganizationLegalAddressRequest\x12,\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x0eorganizationId\x12O\n" +
	"\rlegal_address\x18\x02 \x01(\v2%.command.orgstructure.v1.AddressInputB\x03\xe0A\x02R\flegalAddress\"(\n" +
	"&UpdateOrganizationLegalAddressResponse\"M\n" +
	"\x1dDeactivateOrganizationRequest\x12,\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x0eorganizationId\" \n" +
	"\x1eDeactivateOrganizationResponse\"K\n" +
	"\x1bActivateOrganizationRequest\x12,\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x0eorganizationId\"\x1e\n" +
	"\x1cActivateOrganizationResponse\"I\n" +
	"\x19DeleteOrganizationRequest\x12,\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x0eorganizationId\"\x1c\n" +
	"\x1aDeleteOrganizationResponse\"\xea\x01\n" +
	"\x13CreateClinicRequest\x12,\n" +
	"\x0forganization_id\x18\x01 \x01(\tB\x03\xe0A\x02R\x0eorganizationId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12U\n" +
	"\x10physical_address\x18\x03 \x01(\v2%.command.orgstructure.v1.AddressInputB\x03\xe0A\x02R\x0fphysicalAddress\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"3\n" +
	"\x14CreateClinicResponse\x12\x1b\n" +
	"\tclinic_id\x18\x01 \x01(\tR\bclinicId\"\x8e\x01\n" +
	"\x1aUpdateClinicDetailsRequest\x12 \n" +
	"\tclinic_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bclinicId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\x1d\n" +
	"\x1bUpdateClinicDetailsResponse\"\x9d\x01\n" +
	"\"UpdateClinicPhysicalAddressRequest\x12 \n" +
	"\tclinic_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bclinicId\x12U\n" +
	"\x10physical_address\x18\x02 \x01(\v2%.command.orgstructure.v1.AddressInputB\x03\xe0A\x02R\x0fphysicalAddress\"%\n" +
	"#UpdateClinicPhysicalAddressResponse\";\n" +
	"\x17DeactivateClinicRequest\x12 \n" +
	"\tclinic_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bclinicId\"\x1a\n" +
	"\x18DeactivateClinicResponse\"9\n" +
	"\x15ActivateClinicRequest\x12 \n" +
	"\tclinic_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bclinicId\"\x18\n" +
	"\x16ActivateClinicResponse\"7\n" +
	"\x13DeleteClinicRequest\x12 \n" +
	"\tclinic_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bclinicId\"\x16\n" +
	"\x14DeleteClinicResponse\"\x8b\x01\n" +
	"\x17CreateDepartmentRequest\x12 \n" +
	"\tclinic_id\x18\x01 \x01(\tB\x03\xe0A\x02R\bclinicId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"?\n" +
	"\x18CreateDepartmentResponse\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\tR\fdepartmentId\"\x9a\x01\n" +
	"\x1eUpdateDepartmentDetailsRequest\x12(\n" +
	"\rdepartment_id\x18\x01 \x01(\tB\x03\xe0A\x02R\fdepartmentId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"!\n" +
	"\x1fUpdateDepartmentDetailsResponse\"G\n" +
	"\x1bDeactivateDepartmentRequest\x12(\n" +
	"\rdepartment_id\x18\x01 \x01(\tB\x03\xe0A\x02R\fdepartmentId\"\x1e\n" +
	"\x1cDeactivateDepartmentResponse\"E\n" +
	"\x19ActivateDepartmentRequest\x12(\n" +
	"\rdepartment_id\x18\x01 \x01(\tB\x03\xe0A\x02R\fdepartmentId\"\x1c\n" +
	"\x1aActivateDepartmentResponse\"C\n" +
	"\x17DeleteDepartmentRequest\x12(\n" +
	"\rdepartment_id\x18\x01 \x01(\tB\x03\xe0A\x02R\fdepartmentId\"\x1a\n" +
	"\x18DeleteDepartmentResponse2\x92+\n" +
	"\x1aOrgStructureCommandService\x12\x9b\x01\n" +
	"\x12CreateOrganization\x122.command.orgstructure.v1.CreateOrganizationRequest\x1a3.command.orgstructure.v1.CreateOrganizationResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/organizations\x12\xbe\x02\n" +
	"\x19UpdateOrganizationDetails\x129.command.orgstructure.v1.UpdateOrganizationDetailsRequest\x1a:.command.orgstructure.v1.UpdateOrganizationDetailsResponse\"\xa9\x01\x92ApJn\n" +
	"\x03404\x12g\n" +
	"eNot found. Error codes:\n" +
	"- `organization_not_found` — organization with the given ID does not exist.\x82\xd3\xe4\x93\x020:\x01*\x1a+/v1/organizations/{organization_id}/details\x12\xd3\x02\n" +
	"\x1eUpdateOrganizationLegalAddress\x12>.command.orgstructure.v1.UpdateOrganizationLegalAddressRequest\x1a?.command.orgstructure.v1.UpdateOrganizationLegalAddressResponse\"\xaf\x01\x92ApJn\n" +
	"\x03404\x12g\n" +
	"eNot found. Error codes:\n" +
	"- `organization_not_found` — organization with the given ID does not exist.\x82\xd3\xe4\x93\x026:\x01*\x1a1/v1/organizations/{organization_id}/legal-address\x12\xb8\x02\n" +
	"\x16DeactivateOrganization\x126.command.orgstructure.v1.DeactivateOrganizationRequest\x1a7.command.orgstructure.v1.DeactivateOrganizationResponse\"\xac\x01\x92ApJn\n" +
	"\x03404\x12g\n" +
	"eNot found. Error codes:\n" +
	"- `organization_not_found` — organization with the given ID does not exist.\x82\xd3\xe4\x93\x023:\x01*\"./v1/organizations/{organization_id}/deactivate\x12\xb0\x02\n" +
	"\x14ActivateOrganization\x124.command.orgstructure.v1.ActivateOrganizationRequest\x1a5.command.orgstructure.v1.ActivateOrganizationResponse\"\xaa\x01\x92ApJn\n" +
	"\x03404\x12g\n" +
	"eNot found. Error codes:\n" +
	"- `organization_not_found` — organization with the given ID does not exist.\x82\xd3\xe4\x93\x021:\x01*\",/v1/organizations/{organization_id}/activate\x12\xa7\x03\n" +
	"\x12DeleteOrganization\x122.command.orgstructure.v1.DeleteOrganizationRequest\x1a3.command.orgstructure.v1.DeleteOrganizationResponse\"\xa7\x02\x92A\xf8\x01Jn\n" +
	"\x03404\x12g\n" +
	"eNot found. Error codes:\n" +
	"- `organization_not_found` — organization with the given ID does not exist.J\x85\x01\n" +
	"\x03409\x12~\n" +
	"|Conflict. Error codes:\n" +
	"- `organization_delete_has_dependents` — organization has associated incidents or service requests.\x82\xd3\xe4\x93\x02%*#/v1/organizations/{organization_id}\x12\x9e\x02\n" +
	"\fCreateClinic\x12,.command.orgstructure.v1.CreateClinicRequest\x1a-.command.orgstructure.v1.CreateClinicResponse\"\xb0\x01\x92AwJu\n" +
	"\x03404\x12n\n" +
	"lNot found. Error codes:\n" +
	"- `clinic_organization_not_found` — organization with the given ID does not exist.\x82\xd3\xe4\x93\x020:\x01*\"+/v1/organizations/{organization_id}/clinics\x12\x94\x02\n" +
	"\x13UpdateClinicDetails\x123.command.orgstructure.v1.UpdateClinicDetailsRequest\x1a4.command.orgstructure.v1.UpdateClinicDetailsResponse\"\x91\x01\x92AdJb\n" +
	"\x03404\x12[\n" +
	"YNot found. Error codes:\n" +
	"- `clinic_not_found` — clinic with the given ID does not exist.\x82\xd3\xe4\x93\x02$:\x01*\x1a\x1f/v1/clinics/{clinic_id}/details\x12\xb5\x02\n" +
	"\x1bUpdateClinicPhysicalAddress\x12;.command.orgstructure.v1.UpdateClinicPhysicalAddressRequest\x1a<.command.orgstructure.v1.UpdateClinicPhysicalAddressResponse\"\x9a\x01\x92AdJb\n" +
	"\x03404\x12[\n" +
	"YNot found. Error codes:\n" +
	"- `clinic_not_found` — clinic with the given ID does not exist.\x82\xd3\xe4\x93\x02-:\x01*\x1a(/v1/clinics/{clinic_id}/physical-address\x12\x8e\x02\n" +
	"\x10DeactivateClinic\x120.command.orgstructure.v1.DeactivateClinicRequest\x1a1.command.orgstructure.v1.DeactivateClinicResponse\"\x94\x01\x92AdJb\n" +
	"\x03404\x12[\n" +
	"YNot found. Error codes:\n" +
	"- `clinic_not_found` — clinic with the given ID does not exist.\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/clinics/{clinic_id}/deactivate\x12\x80\x03\n" +
	"\x0eActivateClinic\x12..command.orgstructure.v1.ActivateClinicRequest\x1a/.command.orgstructure.v1.ActivateClinicResponse\"\x8c\x02\x92A\xdd\x01Jb\n" +
	"\x03404\x12[\n" +
	"YNot found. Error codes:\n" +
	"- `clinic_not_found` — clinic with the given ID does not exist.Jw\n" +
	"\x03422\x12p\n" +
	"nBusiness rule violation. Error codes:\n" +
	"- `clinic_activate_parent_inactive` — parent organization is inactive.\x82\xd3\xe4\x93\x02%:\x01*\" /v1/clinics/{clinic_id}/activate\x12\xf0\x02\n" +
	"\fDeleteClinic\x12,.command.orgstructure.v1.DeleteClinicRequest\x1a-.command.orgstructure.v1.DeleteClinicResponse\"\x82\x02\x92A\xdf\x01Jb\n" +
	"\x03404\x12[\n" +
	"YNot found. Error codes:\n" +
	"- `clinic_not_found` — clinic with the given ID does not exist.Jy\n" +
	"\x03409\x12r\n" +
	"pConflict. Error codes:\n" +
	"- `clinic_delete_has_dependents` — clinic has associated incidents or service requests.\x82\xd3\xe4\x93\x02\x19*\x17/v1/clinics/{clinic_id}\x12\x9a\x02\n" +
	"\x10CreateDepartment\x120.command.orgstructure.v1.CreateDepartmentRequest\x1a1.command.orgstructure.v1.CreateDepartmentResponse\"\xa0\x01\x92AoJm\n" +
	"\x03404\x12f\n" +
	"dNot found. Error codes:\n" +
	"- `department_clinic_not_found` — clinic with the given ID does not exist.\x82\xd3\xe4\x93\x02(:\x01*\"#/v1/clinics/{clinic_id}/departments\x12\xb0\x02\n" +
	"\x17UpdateDepartmentDetails\x127.command.orgstructure.v1.UpdateDepartmentDetailsRequest\x1a8.command.orgstructure.v1.UpdateDepartmentDetailsResponse\"\xa1\x01\x92AlJj\n" +
	"\x03404\x12c\n" +
	"aNot found. Error codes:\n" +
	"- `department_not_found` — department with the given ID does not exist.\x82\xd3\xe4\x93\x02,:\x01*\x1a'/v1/departments/{department_id}/details\x12\xaa\x02\n" +
	"\x14DeactivateDepartment\x124.command.orgstructure.v1.DeactivateDepartmentRequest\x1a5.command.orgstructure.v1.DeactivateDepartmentResponse\"\xa4\x01\x92AlJj\n" +
	"\x03404\x12c\n" +
	"aNot found. Error codes:\n" +
	"- `department_not_found` — department with the given ID does not exist.\x82\xd3\xe4\x93\x02/:\x01*\"*/v1/departments/{department_id}/deactivate\x12\x9a\x03\n" +
	"\x12ActivateDepartment\x122.command.orgstructure.v1.ActivateDepartmentRequest\x1a3.command.orgstructure.v1.ActivateDepartmentResponse\"\x9a\x02\x92A\xe3\x01Jj\n" +
	"\x03404\x12c\n" +
	"aNot found. Error codes:\n" +
	"- `department_not_found` — department with the given ID does not exist.Ju\n" +
	"\x03422\x12n\n" +
	"lBusiness rule violation. Error codes:\n" +
	"- `department_activate_parent_inactive` — parent clinic is inactive.\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/departments/{department_id}/activate\x12\x95\x03\n" +
	"\x10DeleteDepartment\x120.command.orgstructure.v1.DeleteDepartmentRequest\x1a1.command.orgstructure.v1.DeleteDepartmentResponse\"\x9b\x02\x92A\xf0\x01Jj\n" +
	"\x03404\x12c\n" +
	"aNot found. Error codes:\n" +
	"- `department_not_found` — department with the given ID does not exist.J\x81\x01\n" +
	"\x03409\x12z\n" +
	"xConflict. Error codes:\n" +
	"- `department_delete_has_dependents` — department has associated incidents or service requests.\x82\xd3\xe4\x93\x02!*\x1f/v1/departments/{department_id}B\xec\x04\x92A\xe3\x02RI\n" +
	"\x03400\x12B\n" +
	"#Validation failed or invalid input.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponseRS\n" +
	"\x03401\x12L\n" +
	"-Unauthenticated — missing or invalid token.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponseR8\n" +
	"\x03403\x121\n" +
	"\x12Permission denied.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponseR>\n" +
	"\x03500\x127\n" +
	"\x18Unexpected server error.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponseRG\n" +
	"\adefault\x12<\n" +
	"\x1dAn unexpected error response.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponse\n" +
	"\x1bcom.command.orgstructure.v1B\x11OrgstructureProtoP\x01ZUgithub.com/medincident/medincident-backend/pkg/command/orgstructure/v1;orgstructurev1\xa2\x02\x03COX\xaa\x02\x17Command.Orgstructure.V1\xca\x02\x17Command\\Orgstructure\\V1\xe2\x02#Command\\Orgstructure\\V1\\GPBMetadata\xea\x02\x19Command::Orgstructure::V1b\x06proto3"

var (
	file_command_orgstructure_v1_orgstructure_proto_rawDescOnce sync.Once
	file_command_orgstructure_v1_orgstructure_proto_rawDescData []byte
)

func file_command_orgstructure_v1_orgstructure_proto_rawDescGZIP() []byte {
	file_command_orgstructure_v1_orgstructure_proto_rawDescOnce.Do(func() {
		file_command_orgstructure_v1_orgstructure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_orgstructure_v1_orgstructure_proto_rawDesc), len(file_command_orgstructure_v1_orgstructure_proto_rawDesc)))
	})
	return file_command_orgstructure_v1_orgstructure_proto_rawDescData
}

var file_command_orgstructure_v1_orgstructure_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_command_orgstructure_v1_orgstructure_proto_goTypes = []any{
	(*PointInput)(nil),                             // 0: command.orgstructure.v1.PointInput
	(*AddressInput)(nil),                           // 1: command.orgstructure.v1.AddressInput
	(*CreateOrganizationRequest)(nil),              // 2: command.orgstructure.v1.CreateOrganizationRequest
	(*CreateOrganizationResponse)(nil),             // 3: command.orgstructure.v1.CreateOrganizationResponse
	(*UpdateOrganizationDetailsRequest)(nil),       // 4: command.orgstructure.v1.UpdateOrganizationDetailsRequest
	(*UpdateOrganizationDetailsResponse)(nil),      // 5: command.orgstructure.v1.UpdateOrganizationDetailsResponse
	(*UpdateOrganizationLegalAddressRequest)(nil),  // 6: command.orgstructure.v1.UpdateOrganizationLegalAddressRequest
	(*UpdateOrganizationLegalAddressResponse)(nil), // 7: command.orgstructure.v1.UpdateOrganizationLegalAddressResponse
	(*DeactivateOrganizationRequest)(nil),          // 8: command.orgstructure.v1.DeactivateOrganizationRequest
	(*DeactivateOrganizationResponse)(nil),         // 9: command.orgstructure.v1.DeactivateOrganizationResponse
	(*ActivateOrganizationRequest)(nil),            // 10: command.orgstructure.v1.ActivateOrganizationRequest
	(*ActivateOrganizationResponse)(nil),           // 11: command.orgstructure.v1.ActivateOrganizationResponse
	(*DeleteOrganizationRequest)(nil),              // 12: command.orgstructure.v1.DeleteOrganizationRequest
	(*DeleteOrganizationResponse)(nil),             // 13: command.orgstructure.v1.DeleteOrganizationResponse
	(*CreateClinicRequest)(nil),                    // 14: command.orgstructure.v1.CreateClinicRequest
	(*CreateClinicResponse)(nil),                   // 15: command.orgstructure.v1.CreateClinicResponse
	(*UpdateClinicDetailsRequest)(nil),             // 16: command.orgstructure.v1.UpdateClinicDetailsRequest
	(*UpdateClinicDetailsResponse)(nil),            // 17: command.orgstructure.v1.UpdateClinicDetailsResponse
	(*UpdateClinicPhysicalAddressRequest)(nil),     // 18: command.orgstructure.v1.UpdateClinicPhysicalAddressRequest
	(*UpdateClinicPhysicalAddressResponse)(nil),    // 19: command.orgstructure.v1.UpdateClinicPhysicalAddressResponse
	(*DeactivateClinicRequest)(nil),                // 20: command.orgstructure.v1.DeactivateClinicRequest
	(*DeactivateClinicResponse)(nil),               // 21: command.orgstructure.v1.DeactivateClinicResponse
	(*ActivateClinicRequest)(nil),                  // 22: command.orgstructure.v1.ActivateClinicRequest
	(*ActivateClinicResponse)(nil),                 // 23: command.orgstructure.v1.ActivateClinicResponse
	(*DeleteClinicRequest)(nil),                    // 24: command.orgstructure.v1.DeleteClinicRequest
	(*DeleteClinicResponse)(nil),                   // 25: command.orgstructure.v1.DeleteClinicResponse
	(*CreateDepartmentRequest)(nil),                // 26: command.orgstructure.v1.CreateDepartmentRequest
	(*CreateDepartmentResponse)(nil),               // 27: command.orgstructure.v1.CreateDepartmentResponse
	(*UpdateDepartmentDetailsRequest)(nil),         // 28: command.orgstructure.v1.UpdateDepartmentDetailsRequest
	(*UpdateDepartmentDetailsResponse)(nil),        // 29: command.orgstructure.v1.UpdateDepartmentDetailsResponse
	(*DeactivateDepartmentRequest)(nil),            // 30: command.orgstructure.v1.DeactivateDepartmentRequest
	(*DeactivateDepartmentResponse)(nil),           // 31: command.orgstructure.v1.DeactivateDepartmentResponse
	(*ActivateDepartmentRequest)(nil),              // 32: command.orgstructure.v1.ActivateDepartmentRequest
	(*ActivateDepartmentResponse)(nil),             // 33: command.orgstructure.v1.ActivateDepartmentResponse
	(*DeleteDepartmentRequest)(nil),                // 34: command.orgstructure.v1.DeleteDepartmentRequest
	(*DeleteDepartmentResponse)(nil),               // 35: command.orgstructure.v1.DeleteDepartmentResponse
}
var file_command_orgstructure_v1_orgstructure_proto_depIdxs = []int32{
	0,  // 0: command.orgstructure.v1.AddressInput.point:type_name -> command.orgstructure.v1.PointInput
	1,  // 1: command.orgstructure.v1.CreateOrganizationRequest.legal_address:type_name -> command.orgstructure.v1.AddressInput
	1,  // 2: command.orgstructure.v1.UpdateOrganizationLegalAddressRequest.legal_address:type_name -> command.orgstructure.v1.AddressInput
	1,  // 3: command.orgstructure.v1.CreateClinicRequest.physical_address:type_name -> command.orgstructure.v1.AddressInput
	1,  // 4: command.orgstructure.v1.UpdateClinicPhysicalAddressRequest.physical_address:type_name -> command.orgstructure.v1.AddressInput
	2,  // 5: command.orgstructure.v1.OrgStructureCommandService.CreateOrganization:input_type -> command.orgstructure.v1.CreateOrganizationRequest
	4,  // 6: command.orgstructure.v1.OrgStructureCommandService.UpdateOrganizationDetails:input_type -> command.orgstructure.v1.UpdateOrganizationDetailsRequest
	6,  // 7: command.orgstructure.v1.OrgStructureCommandService.UpdateOrganizationLegalAddress:input_type -> command.orgstructure.v1.UpdateOrganizationLegalAddressRequest
	8,  // 8: command.orgstructure.v1.OrgStructureCommandService.DeactivateOrganization:input_type -> command.orgstructure.v1.DeactivateOrganizationRequest
	10, // 9: command.orgstructure.v1.OrgStructureCommandService.ActivateOrganization:input_type -> command.orgstructure.v1.ActivateOrganizationRequest
	12, // 10: command.orgstructure.v1.OrgStructureCommandService.DeleteOrganization:input_type -> command.orgstructure.v1.DeleteOrganizationRequest
	14, // 11: command.orgstructure.v1.OrgStructureCommandService.CreateClinic:input_type -> command.orgstructure.v1.CreateClinicRequest
	16, // 12: command.orgstructure.v1.OrgStructureCommandService.UpdateClinicDetails:input_type -> command.orgstructure.v1.UpdateClinicDetailsRequest
	18, // 13: command.orgstructure.v1.OrgStructureCommandService.UpdateClinicPhysicalAddress:input_type -> command.orgstructure.v1.UpdateClinicPhysicalAddressRequest
	20, // 14: command.orgstructure.v1.OrgStructureCommandService.DeactivateClinic:input_type -> command.orgstructure.v1.DeactivateClinicRequest
	22, // 15: command.orgstructure.v1.OrgStructureCommandService.ActivateClinic:input_type -> command.orgstructure.v1.ActivateClinicRequest
	24, // 16: command.orgstructure.v1.OrgStructureCommandService.DeleteClinic:input_type -> command.orgstructure.v1.DeleteClinicRequest
	26, // 17: command.orgstructure.v1.OrgStructureCommandService.CreateDepartment:input_type -> command.orgstructure.v1.CreateDepartmentRequest
	28, // 18: command.orgstructure.v1.OrgStructureCommandService.UpdateDepartmentDetails:input_type -> command.orgstructure.v1.UpdateDepartmentDetailsRequest
	30, // 19: command.orgstructure.v1.OrgStructureCommandService.DeactivateDepartment:input_type -> command.orgstructure.v1.DeactivateDepartmentRequest
	32, // 20: command.orgstructure.v1.OrgStructureCommandService.ActivateDepartment:input_type -> command.orgstructure.v1.ActivateDepartmentRequest
	34, // 21: command.orgstructure.v1.OrgStructureCommandService.DeleteDepartment:input_type -> command.orgstructure.v1.DeleteDepartmentRequest
	3,  // 22: command.orgstructure.v1.OrgStructureCommandService.CreateOrganization:output_type -> command.orgstructure.v1.CreateOrganizationResponse
	5,  // 23: command.orgstructure.v1.OrgStructureCommandService.UpdateOrganizationDetails:output_type -> command.orgstructure.v1.UpdateOrganizationDetailsResponse
	7,  // 24: command.orgstructure.v1.OrgStructureCommandService.UpdateOrganizationLegalAddress:output_type -> command.orgstructure.v1.UpdateOrganizationLegalAddressResponse
	9,  // 25: command.orgstructure.v1.OrgStructureCommandService.DeactivateOrganization:output_type -> command.orgstructure.v1.DeactivateOrganizationResponse
	11, // 26: command.orgstructure.v1.OrgStructureCommandService.ActivateOrganization:output_type -> command.orgstructure.v1.ActivateOrganizationResponse
	13, // 27: command.orgstructure.v1.OrgStructureCommandService.DeleteOrganization:output_type -> command.orgstructure.v1.DeleteOrganizationResponse
	15, // 28: command.orgstructure.v1.OrgStructureCommandService.CreateClinic:output_type -> command.orgstructure.v1.CreateClinicResponse
	17, // 29: command.orgstructure.v1.OrgStructureCommandService.UpdateClinicDetails:output_type -> command.orgstructure.v1.UpdateClinicDetailsResponse
	19, // 30: command.orgstructure.v1.OrgStructureCommandService.UpdateClinicPhysicalAddress:output_type -> command.orgstructure.v1.UpdateClinicPhysicalAddressResponse
	21, // 31: command.orgstructure.v1.OrgStructureCommandService.DeactivateClinic:output_type -> command.orgstructure.v1.DeactivateClinicResponse
	23, // 32: command.orgstructure.v1.OrgStructureCommandService.ActivateClinic:output_type -> command.orgstructure.v1.ActivateClinicResponse
	25, // 33: command.orgstructure.v1.OrgStructureCommandService.DeleteClinic:output_type -> command.orgstructure.v1.DeleteClinicResponse
	27, // 34: command.orgstructure.v1.OrgStructureCommandService.CreateDepartment:output_type -> command.orgstructure.v1.CreateDepartmentResponse
	29, // 35: command.orgstructure.v1.OrgStructureCommandService.UpdateDepartmentDetails:output_type -> command.orgstructure.v1.UpdateDepartmentDetailsResponse
	31, // 36: command.orgstructure.v1.OrgStructureCommandService.DeactivateDepartment:output_type -> command.orgstructure.v1.DeactivateDepartmentResponse
	33, // 37: command.orgstructure.v1.OrgStructureCommandService.ActivateDepartment:output_type -> command.orgstructure.v1.ActivateDepartmentResponse
	35, // 38: command.orgstructure.v1.OrgStructureCommandService.DeleteDepartment:output_type -> command.orgstructure.v1.DeleteDepartmentResponse
	22, // [22:39] is the sub-list for method output_type
	5,  // [5:22] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_command_orgstructure_v1_orgstructure_proto_init() }
func file_command_orgstructure_v1_orgstructure_proto_init() {
	if File_command_orgstructure_v1_orgstructure_proto != nil {
		return
	}
	file_command_orgstructure_v1_orgstructure_proto_msgTypes[1].OneofWrappers = []any{}
	file_command_orgstructure_v1_orgstructure_proto_msgTypes[2].OneofWrappers = []any{}
	file_command_orgstructure_v1_orgstructure_proto_msgTypes[4].OneofWrappers = []any{}
	file_command_orgstructure_v1_orgstructure_proto_msgTypes[14].OneofWrappers = []any{}
	file_command_orgstructure_v1_orgstructure_proto_msgTypes[16].OneofWrappers = []any{}
	file_command_orgstructure_v1_orgstructure_proto_msgTypes[26].OneofWrappers = []any{}
	file_command_orgstructure_v1_orgstructure_proto_msgTypes[28].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_orgstructure_v1_orgstructure_proto_rawDesc), len(file_command_orgstructure_v1_orgstructure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_command_orgstructure_v1_orgstructure_proto_goTypes,
		DependencyIndexes: file_command_orgstructure_v1_orgstructure_proto_depIdxs,
		MessageInfos:      file_command_orgstructure_v1_orgstructure_proto_msgTypes,
	}.Build()
	File_command_orgstructure_v1_orgstructure_proto = out.File
	file_command_orgstructure_v1_orgstructure_proto_goTypes = nil
	file_command_orgstructure_v1_orgstructure_proto_depIdxs = nil
}
