// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: event/employee/v1/events.proto

package employeev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmployeeHired — subject: medincident.event.employee.v1.hired
// aggregate_id = employee UUID
type EmployeeHired struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ZitadelUserId  string                 `protobuf:"bytes,1,opt,name=zitadel_user_id,json=zitadelUserId,proto3" json:"zitadel_user_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	DepartmentId   string                 `protobuf:"bytes,3,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Position       string                 `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"` // empty = not set
	HiredAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=hired_at,json=hiredAt,proto3" json:"hired_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EmployeeHired) Reset() {
	*x = EmployeeHired{}
	mi := &file_event_employee_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeHired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeHired) ProtoMessage() {}

func (x *EmployeeHired) ProtoReflect() protoreflect.Message {
	mi := &file_event_employee_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeHired.ProtoReflect.Descriptor instead.
func (*EmployeeHired) Descriptor() ([]byte, []int) {
	return file_event_employee_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *EmployeeHired) GetZitadelUserId() string {
	if x != nil {
		return x.ZitadelUserId
	}
	return ""
}

func (x *EmployeeHired) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *EmployeeHired) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *EmployeeHired) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *EmployeeHired) GetHiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.HiredAt
	}
	return nil
}

// EmployeePositionChanged — subject: medincident.event.employee.v1.position_changed
type EmployeePositionChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      string                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"` // empty = cleared
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeePositionChanged) Reset() {
	*x = EmployeePositionChanged{}
	mi := &file_event_employee_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeePositionChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeePositionChanged) ProtoMessage() {}

func (x *EmployeePositionChanged) ProtoReflect() protoreflect.Message {
	mi := &file_event_employee_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeePositionChanged.ProtoReflect.Descriptor instead.
func (*EmployeePositionChanged) Descriptor() ([]byte, []int) {
	return file_event_employee_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeePositionChanged) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *EmployeePositionChanged) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// EmployeeDepartmentChanged — subject: medincident.event.employee.v1.department_changed
type EmployeeDepartmentChanged struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NewDepartmentId string                 `protobuf:"bytes,1,opt,name=new_department_id,json=newDepartmentId,proto3" json:"new_department_id,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EmployeeDepartmentChanged) Reset() {
	*x = EmployeeDepartmentChanged{}
	mi := &file_event_employee_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeDepartmentChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeDepartmentChanged) ProtoMessage() {}

func (x *EmployeeDepartmentChanged) ProtoReflect() protoreflect.Message {
	mi := &file_event_employee_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeDepartmentChanged.ProtoReflect.Descriptor instead.
func (*EmployeeDepartmentChanged) Descriptor() ([]byte, []int) {
	return file_event_employee_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *EmployeeDepartmentChanged) GetNewDepartmentId() string {
	if x != nil {
		return x.NewDepartmentId
	}
	return ""
}

func (x *EmployeeDepartmentChanged) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// EmployeeTerminated — subject: medincident.event.employee.v1.terminated
type EmployeeTerminated struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"` // needed for counter decrement
	DepartmentId   string                 `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	TerminatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=terminated_at,json=terminatedAt,proto3" json:"terminated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EmployeeTerminated) Reset() {
	*x = EmployeeTerminated{}
	mi := &file_event_employee_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeTerminated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeTerminated) ProtoMessage() {}

func (x *EmployeeTerminated) ProtoReflect() protoreflect.Message {
	mi := &file_event_employee_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeTerminated.ProtoReflect.Descriptor instead.
func (*EmployeeTerminated) Descriptor() ([]byte, []int) {
	return file_event_employee_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *EmployeeTerminated) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *EmployeeTerminated) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *EmployeeTerminated) GetTerminatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TerminatedAt
	}
	return nil
}

var File_event_employee_v1_events_proto protoreflect.FileDescriptor

const file_event_employee_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1eevent/employee/v1/events.proto\x12\x11event.employee.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n" +
	"\rEmployeeHired\x12&\n" +
	"\x0fzitadel_user_id\x18\x01 \x01(\tR\rzitadelUserId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12#\n" +
	"\rdepartment_id\x18\x03 \x01(\tR\fdepartmentId\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\tR\bposition\x125\n" +
	"\bhired_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ahiredAt\"p\n" +
	"\x17EmployeePositionChanged\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\tR\bposition\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x82\x01\n" +
	"\x19EmployeeDepartmentChanged\x12*\n" +
	"\x11new_department_id\x18\x01 \x01(\tR\x0fnewDepartmentId\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa3\x01\n" +
	"\x12EmployeeTerminated\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\tR\fdepartmentId\x12?\n" +
	"\rterminated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fterminatedAtB\xd7\x01\n" +
	"\x15com.event.employee.v1B\vEventsProtoP\x01ZKgithub.com/medincident/medincident-backend/pkg/event/employee/v1;employeev1\xa2\x02\x03EEX\xaa\x02\x11Event.Employee.V1\xca\x02\x11Event\\Employee\\V1\xe2\x02\x1dEvent\\Employee\\V1\\GPBMetadata\xea\x02\x13Event::Employee::V1b\x06proto3"

var (
	file_event_employee_v1_events_proto_rawDescOnce sync.Once
	file_event_employee_v1_events_proto_rawDescData []byte
)

func file_event_employee_v1_events_proto_rawDescGZIP() []byte {
	file_event_employee_v1_events_proto_rawDescOnce.Do(func() {
		file_event_employee_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_employee_v1_events_proto_rawDesc), len(file_event_employee_v1_events_proto_rawDesc)))
	})
	return file_event_employee_v1_events_proto_rawDescData
}

var file_event_employee_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_event_employee_v1_events_proto_goTypes = []any{
	(*EmployeeHired)(nil),             // 0: event.employee.v1.EmployeeHired
	(*EmployeePositionChanged)(nil),   // 1: event.employee.v1.EmployeePositionChanged
	(*EmployeeDepartmentChanged)(nil), // 2: event.employee.v1.EmployeeDepartmentChanged
	(*EmployeeTerminated)(nil),        // 3: event.employee.v1.EmployeeTerminated
	(*timestamppb.Timestamp)(nil),     // 4: google.protobuf.Timestamp
}
var file_event_employee_v1_events_proto_depIdxs = []int32{
	4, // 0: event.employee.v1.EmployeeHired.hired_at:type_name -> google.protobuf.Timestamp
	4, // 1: event.employee.v1.EmployeePositionChanged.updated_at:type_name -> google.protobuf.Timestamp
	4, // 2: event.employee.v1.EmployeeDepartmentChanged.updated_at:type_name -> google.protobuf.Timestamp
	4, // 3: event.employee.v1.EmployeeTerminated.terminated_at:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_event_employee_v1_events_proto_init() }
func file_event_employee_v1_events_proto_init() {
	if File_event_employee_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_employee_v1_events_proto_rawDesc), len(file_event_employee_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_employee_v1_events_proto_goTypes,
		DependencyIndexes: file_event_employee_v1_events_proto_depIdxs,
		MessageInfos:      file_event_employee_v1_events_proto_msgTypes,
	}.Build()
	File_event_employee_v1_events_proto = out.File
	file_event_employee_v1_events_proto_goTypes = nil
	file_event_employee_v1_events_proto_depIdxs = nil
}
