// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: query/announcement/v1/announcement.proto

package announcementv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/medincident/medincident-backend/pkg/error/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnnouncementPriority int32

const (
	AnnouncementPriority_ANNOUNCEMENT_PRIORITY_UNSPECIFIED AnnouncementPriority = 0
	AnnouncementPriority_ANNOUNCEMENT_PRIORITY_NORMAL      AnnouncementPriority = 1
	AnnouncementPriority_ANNOUNCEMENT_PRIORITY_HIGH        AnnouncementPriority = 2
)

// Enum value maps for AnnouncementPriority.
var (
	AnnouncementPriority_name = map[int32]string{
		0: "ANNOUNCEMENT_PRIORITY_UNSPECIFIED",
		1: "ANNOUNCEMENT_PRIORITY_NORMAL",
		2: "ANNOUNCEMENT_PRIORITY_HIGH",
	}
	AnnouncementPriority_value = map[string]int32{
		"ANNOUNCEMENT_PRIORITY_UNSPECIFIED": 0,
		"ANNOUNCEMENT_PRIORITY_NORMAL":      1,
		"ANNOUNCEMENT_PRIORITY_HIGH":        2,
	}
)

func (x AnnouncementPriority) Enum() *AnnouncementPriority {
	p := new(AnnouncementPriority)
	*p = x
	return p
}

func (x AnnouncementPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnnouncementPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_query_announcement_v1_announcement_proto_enumTypes[0].Descriptor()
}

func (AnnouncementPriority) Type() protoreflect.EnumType {
	return &file_query_announcement_v1_announcement_proto_enumTypes[0]
}

func (x AnnouncementPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnnouncementPriority.Descriptor instead.
func (AnnouncementPriority) EnumDescriptor() ([]byte, []int) {
	return file_query_announcement_v1_announcement_proto_rawDescGZIP(), []int{0}
}

type AnnouncementView struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ClinicId       *string                `protobuf:"bytes,3,opt,name=clinic_id,json=clinicId,proto3,oneof" json:"clinic_id,omitempty"`
	DepartmentId   *string                `protobuf:"bytes,4,opt,name=department_id,json=departmentId,proto3,oneof" json:"department_id,omitempty"`
	AuthorId       string                 `protobuf:"bytes,5,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Title          string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Priority       AnnouncementPriority   `protobuf:"varint,8,opt,name=priority,proto3,enum=query.announcement.v1.AnnouncementPriority" json:"priority,omitempty"`
	IsArchived     bool                   `protobuf:"varint,9,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	StartsAt       *string                `protobuf:"bytes,10,opt,name=starts_at,json=startsAt,proto3,oneof" json:"starts_at,omitempty"` // RFC3339Nano
	EndsAt         *string                `protobuf:"bytes,11,opt,name=ends_at,json=endsAt,proto3,oneof" json:"ends_at,omitempty"`       // RFC3339Nano
	CreatedAt      string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`    // RFC3339Nano
	UpdatedAt      string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`    // RFC3339Nano
	ViewCount      int64                  `protobuf:"varint,14,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnnouncementView) Reset() {
	*x = AnnouncementView{}
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementView) ProtoMessage() {}

func (x *AnnouncementView) ProtoReflect() protoreflect.Message {
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementView.ProtoReflect.Descriptor instead.
func (*AnnouncementView) Descriptor() ([]byte, []int) {
	return file_query_announcement_v1_announcement_proto_rawDescGZIP(), []int{0}
}

func (x *AnnouncementView) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnnouncementView) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *AnnouncementView) GetClinicId() string {
	if x != nil && x.ClinicId != nil {
		return *x.ClinicId
	}
	return ""
}

func (x *AnnouncementView) GetDepartmentId() string {
	if x != nil && x.DepartmentId != nil {
		return *x.DepartmentId
	}
	return ""
}

func (x *AnnouncementView) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *AnnouncementView) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnnouncementView) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AnnouncementView) GetPriority() AnnouncementPriority {
	if x != nil {
		return x.Priority
	}
	return AnnouncementPriority_ANNOUNCEMENT_PRIORITY_UNSPECIFIED
}

func (x *AnnouncementView) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *AnnouncementView) GetStartsAt() string {
	if x != nil && x.StartsAt != nil {
		return *x.StartsAt
	}
	return ""
}

func (x *AnnouncementView) GetEndsAt() string {
	if x != nil && x.EndsAt != nil {
		return *x.EndsAt
	}
	return ""
}

func (x *AnnouncementView) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AnnouncementView) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *AnnouncementView) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

type GetAnnouncementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnnouncementRequest) Reset() {
	*x = GetAnnouncementRequest{}
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementRequest) ProtoMessage() {}

func (x *GetAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*GetAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_query_announcement_v1_announcement_proto_rawDescGZIP(), []int{1}
}

func (x *GetAnnouncementRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAnnouncementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Announcement  *AnnouncementView      `protobuf:"bytes,1,opt,name=announcement,proto3" json:"announcement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnnouncementResponse) Reset() {
	*x = GetAnnouncementResponse{}
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnouncementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementResponse) ProtoMessage() {}

func (x *GetAnnouncementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementResponse.ProtoReflect.Descriptor instead.
func (*GetAnnouncementResponse) Descriptor() ([]byte, []int) {
	return file_query_announcement_v1_announcement_proto_rawDescGZIP(), []int{2}
}

func (x *GetAnnouncementResponse) GetAnnouncement() *AnnouncementView {
	if x != nil {
		return x.Announcement
	}
	return nil
}

type ListAnnouncementsForOrganizationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId  string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,2,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	Priority        AnnouncementPriority   `protobuf:"varint,3,opt,name=priority,proto3,enum=query.announcement.v1.AnnouncementPriority" json:"priority,omitempty"` // UNSPECIFIED = all
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor          *string                `protobuf:"bytes,5,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAnnouncementsForOrganizationRequest) Reset() {
	*x = ListAnnouncementsForOrganizationRequest{}
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementsForOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementsForOrganizationRequest) ProtoMessage() {}

func (x *ListAnnouncementsForOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementsForOrganizationRequest.ProtoReflect.Descriptor instead.
func (*ListAnnouncementsForOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_query_announcement_v1_announcement_proto_rawDescGZIP(), []int{3}
}

func (x *ListAnnouncementsForOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListAnnouncementsForOrganizationRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *ListAnnouncementsForOrganizationRequest) GetPriority() AnnouncementPriority {
	if x != nil {
		return x.Priority
	}
	return AnnouncementPriority_ANNOUNCEMENT_PRIORITY_UNSPECIFIED
}

func (x *ListAnnouncementsForOrganizationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAnnouncementsForOrganizationRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type ListAnnouncementsForOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AnnouncementView    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementsForOrganizationResponse) Reset() {
	*x = ListAnnouncementsForOrganizationResponse{}
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementsForOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementsForOrganizationResponse) ProtoMessage() {}

func (x *ListAnnouncementsForOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementsForOrganizationResponse.ProtoReflect.Descriptor instead.
func (*ListAnnouncementsForOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_query_announcement_v1_announcement_proto_rawDescGZIP(), []int{4}
}

func (x *ListAnnouncementsForOrganizationResponse) GetItems() []*AnnouncementView {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAnnouncementsForOrganizationResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

type ListAnnouncementsForClinicRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClinicId        string                 `protobuf:"bytes,1,opt,name=clinic_id,json=clinicId,proto3" json:"clinic_id,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,2,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	Priority        AnnouncementPriority   `protobuf:"varint,3,opt,name=priority,proto3,enum=query.announcement.v1.AnnouncementPriority" json:"priority,omitempty"`
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor          *string                `protobuf:"bytes,5,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAnnouncementsForClinicRequest) Reset() {
	*x = ListAnnouncementsForClinicRequest{}
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementsForClinicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementsForClinicRequest) ProtoMessage() {}

func (x *ListAnnouncementsForClinicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementsForClinicRequest.ProtoReflect.Descriptor instead.
func (*ListAnnouncementsForClinicRequest) Descriptor() ([]byte, []int) {
	return file_query_announcement_v1_announcement_proto_rawDescGZIP(), []int{5}
}

func (x *ListAnnouncementsForClinicRequest) GetClinicId() string {
	if x != nil {
		return x.ClinicId
	}
	return ""
}

func (x *ListAnnouncementsForClinicRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *ListAnnouncementsForClinicRequest) GetPriority() AnnouncementPriority {
	if x != nil {
		return x.Priority
	}
	return AnnouncementPriority_ANNOUNCEMENT_PRIORITY_UNSPECIFIED
}

func (x *ListAnnouncementsForClinicRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAnnouncementsForClinicRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type ListAnnouncementsForClinicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AnnouncementView    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementsForClinicResponse) Reset() {
	*x = ListAnnouncementsForClinicResponse{}
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementsForClinicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementsForClinicResponse) ProtoMessage() {}

func (x *ListAnnouncementsForClinicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementsForClinicResponse.ProtoReflect.Descriptor instead.
func (*ListAnnouncementsForClinicResponse) Descriptor() ([]byte, []int) {
	return file_query_announcement_v1_announcement_proto_rawDescGZIP(), []int{6}
}

func (x *ListAnnouncementsForClinicResponse) GetItems() []*AnnouncementView {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAnnouncementsForClinicResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

type ListAnnouncementsForDepartmentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId    string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,2,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	Priority        AnnouncementPriority   `protobuf:"varint,3,opt,name=priority,proto3,enum=query.announcement.v1.AnnouncementPriority" json:"priority,omitempty"`
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor          *string                `protobuf:"bytes,5,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAnnouncementsForDepartmentRequest) Reset() {
	*x = ListAnnouncementsForDepartmentRequest{}
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementsForDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementsForDepartmentRequest) ProtoMessage() {}

func (x *ListAnnouncementsForDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementsForDepartmentRequest.ProtoReflect.Descriptor instead.
func (*ListAnnouncementsForDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_query_announcement_v1_announcement_proto_rawDescGZIP(), []int{7}
}

func (x *ListAnnouncementsForDepartmentRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *ListAnnouncementsForDepartmentRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *ListAnnouncementsForDepartmentRequest) GetPriority() AnnouncementPriority {
	if x != nil {
		return x.Priority
	}
	return AnnouncementPriority_ANNOUNCEMENT_PRIORITY_UNSPECIFIED
}

func (x *ListAnnouncementsForDepartmentRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAnnouncementsForDepartmentRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type ListAnnouncementsForDepartmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AnnouncementView    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAnnouncementsForDepartmentResponse) Reset() {
	*x = ListAnnouncementsForDepartmentResponse{}
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAnnouncementsForDepartmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnnouncementsForDepartmentResponse) ProtoMessage() {}

func (x *ListAnnouncementsForDepartmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_announcement_v1_announcement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnnouncementsForDepartmentResponse.ProtoReflect.Descriptor instead.
func (*ListAnnouncementsForDepartmentResponse) Descriptor() ([]byte, []int) {
	return file_query_announcement_v1_announcement_proto_rawDescGZIP(), []int{8}
}

func (x *ListAnnouncementsForDepartmentResponse) GetItems() []*AnnouncementView {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAnnouncementsForDepartmentResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

var File_query_announcement_v1_announcement_proto protoreflect.FileDescriptor

const file_query_announcement_v1_announcement_proto_rawDesc = "" +
	"\n" +
	"(query/announcement/v1/announcement.proto\x12\x15query.announcement.v1\x1a\x14error/v1/error.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa5\x04\n" +
	"\x10AnnouncementView\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12 \n" +
	"\tclinic_id\x18\x03 \x01(\tH\x00R\bclinicId\x88\x01\x01\x12(\n" +
	"\rdepartment_id\x18\x04 \x01(\tH\x01R\fdepartmentId\x88\x01\x01\x12\x1b\n" +
	"\tauthor_id\x18\x05 \x01(\tR\bauthorId\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x12G\n" +
	"\bpriority\x18\b \x01(\x0e2+.query.announcement.v1.AnnouncementPriorityR\bpriority\x12\x1f\n" +
	"\vis_archived\x18\t \x01(\bR\n" +
	"isArchived\x12 \n" +
	"\tstarts_at\x18\n" +
	" \x01(\tH\x02R\bstartsAt\x88\x01\x01\x12\x1c\n" +
	"\aends_at\x18\v \x01(\tH\x03R\x06endsAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"view_count\x18\x0e \x01(\x03R\tviewCountB\f\n" +
	"\n" +
	"_clinic_idB\x10\n" +
	"\x0e_department_idB\f\n" +
	"\n" +
	"_starts_atB\n" +
	"\n" +
	"\b_ends_at\"(\n" +
	"\x16GetAnnouncementRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"f\n" +
	"\x17GetAnnouncementResponse\x12K\n" +
	"\fannouncement\x18\x01 \x01(\v2'.query.announcement.v1.AnnouncementViewR\fannouncement\"\x84\x02\n" +
	"'ListAnnouncementsForOrganizationRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12)\n" +
	"\x10include_archived\x18\x02 \x01(\bR\x0fincludeArchived\x12G\n" +
	"\bpriority\x18\x03 \x01(\x0e2+.query.announcement.v1.AnnouncementPriorityR\bpriority\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x05 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\x9f\x01\n" +
	"(ListAnnouncementsForOrganizationResponse\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.query.announcement.v1.AnnouncementViewR\x05items\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"\xf2\x01\n" +
	"!ListAnnouncementsForClinicRequest\x12\x1b\n" +
	"\tclinic_id\x18\x01 \x01(\tR\bclinicId\x12)\n" +
	"\x10include_archived\x18\x02 \x01(\bR\x0fincludeArchived\x12G\n" +
	"\bpriority\x18\x03 \x01(\x0e2+.query.announcement.v1.AnnouncementPriorityR\bpriority\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x05 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\x99\x01\n" +
	"\"ListAnnouncementsForClinicResponse\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.query.announcement.v1.AnnouncementViewR\x05items\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"\xfe\x01\n" +
	"%ListAnnouncementsForDepartmentRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\tR\fdepartmentId\x12)\n" +
	"\x10include_archived\x18\x02 \x01(\bR\x0fincludeArchived\x12G\n" +
	"\bpriority\x18\x03 \x01(\x0e2+.query.announcement.v1.AnnouncementPriorityR\bpriority\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x05 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\x9d\x01\n" +
	"&ListAnnouncementsForDepartmentResponse\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.query.announcement.v1.AnnouncementViewR\x05items\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor*\x7f\n" +
	"\x14AnnouncementPriority\x12%\n" +
	"!ANNOUNCEMENT_PRIORITY_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cANNOUNCEMENT_PRIORITY_NORMAL\x10\x01\x12\x1e\n" +
	"\x1aANNOUNCEMENT_PRIORITY_HIGH\x10\x022\xbb\b\n" +
	"\x18AnnouncementQueryService\x12\x91\x03\n" +
	"\x0fGetAnnouncement\x12-.query.announcement.v1.GetAnnouncementRequest\x1a..query.announcement.v1.GetAnnouncementResponse\"\x9e\x02\x92A\xf6\x01J\xf3\x01\n" +
	"\x03404\x12\xeb\x01\n" +
	"kNot found. Error codes:\n" +
	"- `announcement_query_not_found` — announcement with the given ID does not exist.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponse\"_\n" +
	"\x10application/json\x12K{\"code\":\"announcement_query_not_found\",\"message\":\"Announcement not found.\"}\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/query/announcements/{id}\x12\xe4\x01\n" +
	" ListAnnouncementsForOrganization\x12>.query.announcement.v1.ListAnnouncementsForOrganizationRequest\x1a?.query.announcement.v1.ListAnnouncementsForOrganizationResponse\"?\x82\xd3\xe4\x93\x029\x127/v1/query/organizations/{organization_id}/announcements\x12\xc6\x01\n" +
	"\x1aListAnnouncementsForClinic\x128.query.announcement.v1.ListAnnouncementsForClinicRequest\x1a9.query.announcement.v1.ListAnnouncementsForClinicResponse\"3\x82\xd3\xe4\x93\x02-\x12+/v1/query/clinics/{clinic_id}/announcements\x12\xda\x01\n" +
	"\x1eListAnnouncementsForDepartment\x12<.query.announcement.v1.ListAnnouncementsForDepartmentRequest\x1a=.query.announcement.v1.ListAnnouncementsForDepartmentResponse\";\x82\xd3\xe4\x93\x025\x123/v1/query/departments/{department_id}/announcementsB\x8e\t\x92A\x91\aR\x89\x02\n" +
	"\x03400\x12\x81\x02\n" +
	"#Validation failed or invalid input.\x12%\n" +
	"#\x1a!.error.v1.ValidationErrorResponse\"\xb2\x01\n" +
	"\x10application/json\x12\x9d\x01{\"code\":\"validation_failed\",\"message\":\"Validation failed.\",\"details\":{\"violations\":[{\"field\":\"field_name\",\"rule\":\"required\",\"message\":\"field is required\"}]}}R\xa0\x01\n" +
	"\x03401\x12\x98\x01\n" +
	"-Unauthenticated — missing or invalid token.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponse\"J\n" +
	"\x10application/json\x126{\"code\":\"unauthenticated\",\"message\":\"unauthenticated\"}R\x89\x01\n" +
	"\x03403\x12\x81\x01\n" +
	"\x12Permission denied.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponse\"N\n" +
	"\x10application/json\x12:{\"code\":\"permission_denied\",\"message\":\"permission denied\"}R\x8b\x01\n" +
	"\x03500\x12\x83\x01\n" +
	"\x18Unexpected server error.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponse\"J\n" +
	"\x10application/json\x126{\"code\":\"unexpected_error\",\"message\":\"internal error\"}R\xc5\x01\n" +
	"\adefault\x12\xb9\x01\n" +
	"JAn unexpected error response (e.g. deadline exceeded or request canceled).\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponse\"N\n" +
	"\x10application/json\x12:{\"code\":\"deadline_exceeded\",\"message\":\"deadline exceeded\"}\n" +
	"\x19com.query.announcement.v1B\x11AnnouncementProtoP\x01ZSgithub.com/medincident/medincident-backend/pkg/query/announcement/v1;announcementv1\xa2\x02\x03QAX\xaa\x02\x15Query.Announcement.V1\xca\x02\x15Query\\Announcement\\V1\xe2\x02!Query\\Announcement\\V1\\GPBMetadata\xea\x02\x17Query::Announcement::V1b\x06proto3"

var (
	file_query_announcement_v1_announcement_proto_rawDescOnce sync.Once
	file_query_announcement_v1_announcement_proto_rawDescData []byte
)

func file_query_announcement_v1_announcement_proto_rawDescGZIP() []byte {
	file_query_announcement_v1_announcement_proto_rawDescOnce.Do(func() {
		file_query_announcement_v1_announcement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_announcement_v1_announcement_proto_rawDesc), len(file_query_announcement_v1_announcement_proto_rawDesc)))
	})
	return file_query_announcement_v1_announcement_proto_rawDescData
}

var file_query_announcement_v1_announcement_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_query_announcement_v1_announcement_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_query_announcement_v1_announcement_proto_goTypes = []any{
	(AnnouncementPriority)(0),                        // 0: query.announcement.v1.AnnouncementPriority
	(*AnnouncementView)(nil),                         // 1: query.announcement.v1.AnnouncementView
	(*GetAnnouncementRequest)(nil),                   // 2: query.announcement.v1.GetAnnouncementRequest
	(*GetAnnouncementResponse)(nil),                  // 3: query.announcement.v1.GetAnnouncementResponse
	(*ListAnnouncementsForOrganizationRequest)(nil),  // 4: query.announcement.v1.ListAnnouncementsForOrganizationRequest
	(*ListAnnouncementsForOrganizationResponse)(nil), // 5: query.announcement.v1.ListAnnouncementsForOrganizationResponse
	(*ListAnnouncementsForClinicRequest)(nil),        // 6: query.announcement.v1.ListAnnouncementsForClinicRequest
	(*ListAnnouncementsForClinicResponse)(nil),       // 7: query.announcement.v1.ListAnnouncementsForClinicResponse
	(*ListAnnouncementsForDepartmentRequest)(nil),    // 8: query.announcement.v1.ListAnnouncementsForDepartmentRequest
	(*ListAnnouncementsForDepartmentResponse)(nil),   // 9: query.announcement.v1.ListAnnouncementsForDepartmentResponse
}
var file_query_announcement_v1_announcement_proto_depIdxs = []int32{
	0,  // 0: query.announcement.v1.AnnouncementView.priority:type_name -> query.announcement.v1.AnnouncementPriority
	1,  // 1: query.announcement.v1.GetAnnouncementResponse.announcement:type_name -> query.announcement.v1.AnnouncementView
	0,  // 2: query.announcement.v1.ListAnnouncementsForOrganizationRequest.priority:type_name -> query.announcement.v1.AnnouncementPriority
	1,  // 3: query.announcement.v1.ListAnnouncementsForOrganizationResponse.items:type_name -> query.announcement.v1.AnnouncementView
	0,  // 4: query.announcement.v1.ListAnnouncementsForClinicRequest.priority:type_name -> query.announcement.v1.AnnouncementPriority
	1,  // 5: query.announcement.v1.ListAnnouncementsForClinicResponse.items:type_name -> query.announcement.v1.AnnouncementView
	0,  // 6: query.announcement.v1.ListAnnouncementsForDepartmentRequest.priority:type_name -> query.announcement.v1.AnnouncementPriority
	1,  // 7: query.announcement.v1.ListAnnouncementsForDepartmentResponse.items:type_name -> query.announcement.v1.AnnouncementView
	2,  // 8: query.announcement.v1.AnnouncementQueryService.GetAnnouncement:input_type -> query.announcement.v1.GetAnnouncementRequest
	4,  // 9: query.announcement.v1.AnnouncementQueryService.ListAnnouncementsForOrganization:input_type -> query.announcement.v1.ListAnnouncementsForOrganizationRequest
	6,  // 10: query.announcement.v1.AnnouncementQueryService.ListAnnouncementsForClinic:input_type -> query.announcement.v1.ListAnnouncementsForClinicRequest
	8,  // 11: query.announcement.v1.AnnouncementQueryService.ListAnnouncementsForDepartment:input_type -> query.announcement.v1.ListAnnouncementsForDepartmentRequest
	3,  // 12: query.announcement.v1.AnnouncementQueryService.GetAnnouncement:output_type -> query.announcement.v1.GetAnnouncementResponse
	5,  // 13: query.announcement.v1.AnnouncementQueryService.ListAnnouncementsForOrganization:output_type -> query.announcement.v1.ListAnnouncementsForOrganizationResponse
	7,  // 14: query.announcement.v1.AnnouncementQueryService.ListAnnouncementsForClinic:output_type -> query.announcement.v1.ListAnnouncementsForClinicResponse
	9,  // 15: query.announcement.v1.AnnouncementQueryService.ListAnnouncementsForDepartment:output_type -> query.announcement.v1.ListAnnouncementsForDepartmentResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_query_announcement_v1_announcement_proto_init() }
func file_query_announcement_v1_announcement_proto_init() {
	if File_query_announcement_v1_announcement_proto != nil {
		return
	}
	file_query_announcement_v1_announcement_proto_msgTypes[0].OneofWrappers = []any{}
	file_query_announcement_v1_announcement_proto_msgTypes[3].OneofWrappers = []any{}
	file_query_announcement_v1_announcement_proto_msgTypes[4].OneofWrappers = []any{}
	file_query_announcement_v1_announcement_proto_msgTypes[5].OneofWrappers = []any{}
	file_query_announcement_v1_announcement_proto_msgTypes[6].OneofWrappers = []any{}
	file_query_announcement_v1_announcement_proto_msgTypes[7].OneofWrappers = []any{}
	file_query_announcement_v1_announcement_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_announcement_v1_announcement_proto_rawDesc), len(file_query_announcement_v1_announcement_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_announcement_v1_announcement_proto_goTypes,
		DependencyIndexes: file_query_announcement_v1_announcement_proto_depIdxs,
		EnumInfos:         file_query_announcement_v1_announcement_proto_enumTypes,
		MessageInfos:      file_query_announcement_v1_announcement_proto_msgTypes,
	}.Build()
	File_query_announcement_v1_announcement_proto = out.File
	file_query_announcement_v1_announcement_proto_goTypes = nil
	file_query_announcement_v1_announcement_proto_depIdxs = nil
}
