// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: command/membership/v1/membership.proto

package membershipv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MembershipCommandService_HireEmployee_FullMethodName                       = "/command.membership.v1.MembershipCommandService/HireEmployee"
	MembershipCommandService_UpdateEmployeePosition_FullMethodName             = "/command.membership.v1.MembershipCommandService/UpdateEmployeePosition"
	MembershipCommandService_UpdateEmployeeDepartment_FullMethodName           = "/command.membership.v1.MembershipCommandService/UpdateEmployeeDepartment"
	MembershipCommandService_TerminateEmployee_FullMethodName                  = "/command.membership.v1.MembershipCommandService/TerminateEmployee"
	MembershipCommandService_DeactivateEmployee_FullMethodName                 = "/command.membership.v1.MembershipCommandService/DeactivateEmployee"
	MembershipCommandService_ActivateEmployee_FullMethodName                   = "/command.membership.v1.MembershipCommandService/ActivateEmployee"
	MembershipCommandService_StartVacationNow_FullMethodName                   = "/command.membership.v1.MembershipCommandService/StartVacationNow"
	MembershipCommandService_ScheduleVacation_FullMethodName                   = "/command.membership.v1.MembershipCommandService/ScheduleVacation"
	MembershipCommandService_UpdateVacationEndDate_FullMethodName              = "/command.membership.v1.MembershipCommandService/UpdateVacationEndDate"
	MembershipCommandService_ForceEndVacation_FullMethodName                   = "/command.membership.v1.MembershipCommandService/ForceEndVacation"
	MembershipCommandService_CancelScheduledVacation_FullMethodName            = "/command.membership.v1.MembershipCommandService/CancelScheduledVacation"
	MembershipCommandService_AssignDepartmentResponsible_FullMethodName        = "/command.membership.v1.MembershipCommandService/AssignDepartmentResponsible"
	MembershipCommandService_RevokeDepartmentResponsible_FullMethodName        = "/command.membership.v1.MembershipCommandService/RevokeDepartmentResponsible"
	MembershipCommandService_AssignDepartmentResponsibleDeputy_FullMethodName  = "/command.membership.v1.MembershipCommandService/AssignDepartmentResponsibleDeputy"
	MembershipCommandService_RemoveDepartmentResponsibleDeputy_FullMethodName  = "/command.membership.v1.MembershipCommandService/RemoveDepartmentResponsibleDeputy"
	MembershipCommandService_AssignClinicHead_FullMethodName                   = "/command.membership.v1.MembershipCommandService/AssignClinicHead"
	MembershipCommandService_RevokeClinicHead_FullMethodName                   = "/command.membership.v1.MembershipCommandService/RevokeClinicHead"
	MembershipCommandService_AssignClinicHeadDeputy_FullMethodName             = "/command.membership.v1.MembershipCommandService/AssignClinicHeadDeputy"
	MembershipCommandService_RemoveClinicHeadDeputy_FullMethodName             = "/command.membership.v1.MembershipCommandService/RemoveClinicHeadDeputy"
	MembershipCommandService_AssignOrganizationAdmin_FullMethodName            = "/command.membership.v1.MembershipCommandService/AssignOrganizationAdmin"
	MembershipCommandService_RevokeOrganizationAdmin_FullMethodName            = "/command.membership.v1.MembershipCommandService/RevokeOrganizationAdmin"
	MembershipCommandService_AssignOrganizationAdminDeputy_FullMethodName      = "/command.membership.v1.MembershipCommandService/AssignOrganizationAdminDeputy"
	MembershipCommandService_RemoveOrganizationAdminDeputy_FullMethodName      = "/command.membership.v1.MembershipCommandService/RemoveOrganizationAdminDeputy"
	MembershipCommandService_AssignOrganizationHead_FullMethodName             = "/command.membership.v1.MembershipCommandService/AssignOrganizationHead"
	MembershipCommandService_RevokeOrganizationHead_FullMethodName             = "/command.membership.v1.MembershipCommandService/RevokeOrganizationHead"
	MembershipCommandService_AssignOrganizationHeadDeputy_FullMethodName       = "/command.membership.v1.MembershipCommandService/AssignOrganizationHeadDeputy"
	MembershipCommandService_RemoveOrganizationHeadDeputy_FullMethodName       = "/command.membership.v1.MembershipCommandService/RemoveOrganizationHeadDeputy"
	MembershipCommandService_AssignOrganizationDispatcher_FullMethodName       = "/command.membership.v1.MembershipCommandService/AssignOrganizationDispatcher"
	MembershipCommandService_RevokeOrganizationDispatcher_FullMethodName       = "/command.membership.v1.MembershipCommandService/RevokeOrganizationDispatcher"
	MembershipCommandService_AssignOrganizationDispatcherDeputy_FullMethodName = "/command.membership.v1.MembershipCommandService/AssignOrganizationDispatcherDeputy"
	MembershipCommandService_RemoveOrganizationDispatcherDeputy_FullMethodName = "/command.membership.v1.MembershipCommandService/RemoveOrganizationDispatcherDeputy"
	MembershipCommandService_GrantSystemAdmin_FullMethodName                   = "/command.membership.v1.MembershipCommandService/GrantSystemAdmin"
	MembershipCommandService_RevokeSystemAdmin_FullMethodName                  = "/command.membership.v1.MembershipCommandService/RevokeSystemAdmin"
)

// MembershipCommandServiceClient is the client API for MembershipCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MembershipService is the command-side contract for who-works-where
// data. It covers the Employee lifecycle (hire / update / terminate),
// Vacation lifecycle (start / schedule / end / cancel / change),
// role grants with deputy management for DepartmentResponsible,
// ClinicHead, OrganizationAdmin, OrganizationHead, and
// OrganizationDispatcher, plus the global SystemAdmin grant that
// operates directly on Zitadel user identifiers.
type MembershipCommandServiceClient interface {
	// Employee lifecycle
	HireEmployee(ctx context.Context, in *HireEmployeeRequest, opts ...grpc.CallOption) (*HireEmployeeResponse, error)
	UpdateEmployeePosition(ctx context.Context, in *UpdateEmployeePositionRequest, opts ...grpc.CallOption) (*UpdateEmployeePositionResponse, error)
	UpdateEmployeeDepartment(ctx context.Context, in *UpdateEmployeeDepartmentRequest, opts ...grpc.CallOption) (*UpdateEmployeeDepartmentResponse, error)
	TerminateEmployee(ctx context.Context, in *TerminateEmployeeRequest, opts ...grpc.CallOption) (*TerminateEmployeeResponse, error)
	DeactivateEmployee(ctx context.Context, in *DeactivateEmployeeRequest, opts ...grpc.CallOption) (*DeactivateEmployeeResponse, error)
	ActivateEmployee(ctx context.Context, in *ActivateEmployeeRequest, opts ...grpc.CallOption) (*ActivateEmployeeResponse, error)
	// Vacation lifecycle
	StartVacationNow(ctx context.Context, in *StartVacationNowRequest, opts ...grpc.CallOption) (*StartVacationNowResponse, error)
	ScheduleVacation(ctx context.Context, in *ScheduleVacationRequest, opts ...grpc.CallOption) (*ScheduleVacationResponse, error)
	UpdateVacationEndDate(ctx context.Context, in *UpdateVacationEndDateRequest, opts ...grpc.CallOption) (*UpdateVacationEndDateResponse, error)
	ForceEndVacation(ctx context.Context, in *ForceEndVacationRequest, opts ...grpc.CallOption) (*ForceEndVacationResponse, error)
	CancelScheduledVacation(ctx context.Context, in *CancelScheduledVacationRequest, opts ...grpc.CallOption) (*CancelScheduledVacationResponse, error)
	// ------ DepartmentResponsible ------
	AssignDepartmentResponsible(ctx context.Context, in *AssignDepartmentResponsibleRequest, opts ...grpc.CallOption) (*AssignDepartmentResponsibleResponse, error)
	RevokeDepartmentResponsible(ctx context.Context, in *RevokeDepartmentResponsibleRequest, opts ...grpc.CallOption) (*RevokeDepartmentResponsibleResponse, error)
	AssignDepartmentResponsibleDeputy(ctx context.Context, in *AssignDepartmentResponsibleDeputyRequest, opts ...grpc.CallOption) (*AssignDepartmentResponsibleDeputyResponse, error)
	RemoveDepartmentResponsibleDeputy(ctx context.Context, in *RemoveDepartmentResponsibleDeputyRequest, opts ...grpc.CallOption) (*RemoveDepartmentResponsibleDeputyResponse, error)
	// ------ ClinicHead ------
	AssignClinicHead(ctx context.Context, in *AssignClinicHeadRequest, opts ...grpc.CallOption) (*AssignClinicHeadResponse, error)
	RevokeClinicHead(ctx context.Context, in *RevokeClinicHeadRequest, opts ...grpc.CallOption) (*RevokeClinicHeadResponse, error)
	AssignClinicHeadDeputy(ctx context.Context, in *AssignClinicHeadDeputyRequest, opts ...grpc.CallOption) (*AssignClinicHeadDeputyResponse, error)
	RemoveClinicHeadDeputy(ctx context.Context, in *RemoveClinicHeadDeputyRequest, opts ...grpc.CallOption) (*RemoveClinicHeadDeputyResponse, error)
	// ------ OrganizationAdmin ------
	AssignOrganizationAdmin(ctx context.Context, in *AssignOrganizationAdminRequest, opts ...grpc.CallOption) (*AssignOrganizationAdminResponse, error)
	RevokeOrganizationAdmin(ctx context.Context, in *RevokeOrganizationAdminRequest, opts ...grpc.CallOption) (*RevokeOrganizationAdminResponse, error)
	AssignOrganizationAdminDeputy(ctx context.Context, in *AssignOrganizationAdminDeputyRequest, opts ...grpc.CallOption) (*AssignOrganizationAdminDeputyResponse, error)
	RemoveOrganizationAdminDeputy(ctx context.Context, in *RemoveOrganizationAdminDeputyRequest, opts ...grpc.CallOption) (*RemoveOrganizationAdminDeputyResponse, error)
	// ------ OrganizationHead ------
	AssignOrganizationHead(ctx context.Context, in *AssignOrganizationHeadRequest, opts ...grpc.CallOption) (*AssignOrganizationHeadResponse, error)
	RevokeOrganizationHead(ctx context.Context, in *RevokeOrganizationHeadRequest, opts ...grpc.CallOption) (*RevokeOrganizationHeadResponse, error)
	AssignOrganizationHeadDeputy(ctx context.Context, in *AssignOrganizationHeadDeputyRequest, opts ...grpc.CallOption) (*AssignOrganizationHeadDeputyResponse, error)
	RemoveOrganizationHeadDeputy(ctx context.Context, in *RemoveOrganizationHeadDeputyRequest, opts ...grpc.CallOption) (*RemoveOrganizationHeadDeputyResponse, error)
	// ------ OrganizationDispatcher ------
	AssignOrganizationDispatcher(ctx context.Context, in *AssignOrganizationDispatcherRequest, opts ...grpc.CallOption) (*AssignOrganizationDispatcherResponse, error)
	RevokeOrganizationDispatcher(ctx context.Context, in *RevokeOrganizationDispatcherRequest, opts ...grpc.CallOption) (*RevokeOrganizationDispatcherResponse, error)
	AssignOrganizationDispatcherDeputy(ctx context.Context, in *AssignOrganizationDispatcherDeputyRequest, opts ...grpc.CallOption) (*AssignOrganizationDispatcherDeputyResponse, error)
	RemoveOrganizationDispatcherDeputy(ctx context.Context, in *RemoveOrganizationDispatcherDeputyRequest, opts ...grpc.CallOption) (*RemoveOrganizationDispatcherDeputyResponse, error)
	// ------ SystemAdmin ------
	GrantSystemAdmin(ctx context.Context, in *GrantSystemAdminRequest, opts ...grpc.CallOption) (*GrantSystemAdminResponse, error)
	RevokeSystemAdmin(ctx context.Context, in *RevokeSystemAdminRequest, opts ...grpc.CallOption) (*RevokeSystemAdminResponse, error)
}

type membershipCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMembershipCommandServiceClient(cc grpc.ClientConnInterface) MembershipCommandServiceClient {
	return &membershipCommandServiceClient{cc}
}

func (c *membershipCommandServiceClient) HireEmployee(ctx context.Context, in *HireEmployeeRequest, opts ...grpc.CallOption) (*HireEmployeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HireEmployeeResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_HireEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) UpdateEmployeePosition(ctx context.Context, in *UpdateEmployeePositionRequest, opts ...grpc.CallOption) (*UpdateEmployeePositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEmployeePositionResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_UpdateEmployeePosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) UpdateEmployeeDepartment(ctx context.Context, in *UpdateEmployeeDepartmentRequest, opts ...grpc.CallOption) (*UpdateEmployeeDepartmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEmployeeDepartmentResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_UpdateEmployeeDepartment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) TerminateEmployee(ctx context.Context, in *TerminateEmployeeRequest, opts ...grpc.CallOption) (*TerminateEmployeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateEmployeeResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_TerminateEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) DeactivateEmployee(ctx context.Context, in *DeactivateEmployeeRequest, opts ...grpc.CallOption) (*DeactivateEmployeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateEmployeeResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_DeactivateEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) ActivateEmployee(ctx context.Context, in *ActivateEmployeeRequest, opts ...grpc.CallOption) (*ActivateEmployeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateEmployeeResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_ActivateEmployee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) StartVacationNow(ctx context.Context, in *StartVacationNowRequest, opts ...grpc.CallOption) (*StartVacationNowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVacationNowResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_StartVacationNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) ScheduleVacation(ctx context.Context, in *ScheduleVacationRequest, opts ...grpc.CallOption) (*ScheduleVacationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScheduleVacationResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_ScheduleVacation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) UpdateVacationEndDate(ctx context.Context, in *UpdateVacationEndDateRequest, opts ...grpc.CallOption) (*UpdateVacationEndDateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVacationEndDateResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_UpdateVacationEndDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) ForceEndVacation(ctx context.Context, in *ForceEndVacationRequest, opts ...grpc.CallOption) (*ForceEndVacationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceEndVacationResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_ForceEndVacation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) CancelScheduledVacation(ctx context.Context, in *CancelScheduledVacationRequest, opts ...grpc.CallOption) (*CancelScheduledVacationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelScheduledVacationResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_CancelScheduledVacation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) AssignDepartmentResponsible(ctx context.Context, in *AssignDepartmentResponsibleRequest, opts ...grpc.CallOption) (*AssignDepartmentResponsibleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignDepartmentResponsibleResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_AssignDepartmentResponsible_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) RevokeDepartmentResponsible(ctx context.Context, in *RevokeDepartmentResponsibleRequest, opts ...grpc.CallOption) (*RevokeDepartmentResponsibleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeDepartmentResponsibleResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_RevokeDepartmentResponsible_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) AssignDepartmentResponsibleDeputy(ctx context.Context, in *AssignDepartmentResponsibleDeputyRequest, opts ...grpc.CallOption) (*AssignDepartmentResponsibleDeputyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignDepartmentResponsibleDeputyResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_AssignDepartmentResponsibleDeputy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) RemoveDepartmentResponsibleDeputy(ctx context.Context, in *RemoveDepartmentResponsibleDeputyRequest, opts ...grpc.CallOption) (*RemoveDepartmentResponsibleDeputyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveDepartmentResponsibleDeputyResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_RemoveDepartmentResponsibleDeputy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) AssignClinicHead(ctx context.Context, in *AssignClinicHeadRequest, opts ...grpc.CallOption) (*AssignClinicHeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignClinicHeadResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_AssignClinicHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) RevokeClinicHead(ctx context.Context, in *RevokeClinicHeadRequest, opts ...grpc.CallOption) (*RevokeClinicHeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeClinicHeadResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_RevokeClinicHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) AssignClinicHeadDeputy(ctx context.Context, in *AssignClinicHeadDeputyRequest, opts ...grpc.CallOption) (*AssignClinicHeadDeputyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignClinicHeadDeputyResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_AssignClinicHeadDeputy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) RemoveClinicHeadDeputy(ctx context.Context, in *RemoveClinicHeadDeputyRequest, opts ...grpc.CallOption) (*RemoveClinicHeadDeputyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveClinicHeadDeputyResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_RemoveClinicHeadDeputy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) AssignOrganizationAdmin(ctx context.Context, in *AssignOrganizationAdminRequest, opts ...grpc.CallOption) (*AssignOrganizationAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignOrganizationAdminResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_AssignOrganizationAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) RevokeOrganizationAdmin(ctx context.Context, in *RevokeOrganizationAdminRequest, opts ...grpc.CallOption) (*RevokeOrganizationAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeOrganizationAdminResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_RevokeOrganizationAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) AssignOrganizationAdminDeputy(ctx context.Context, in *AssignOrganizationAdminDeputyRequest, opts ...grpc.CallOption) (*AssignOrganizationAdminDeputyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignOrganizationAdminDeputyResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_AssignOrganizationAdminDeputy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) RemoveOrganizationAdminDeputy(ctx context.Context, in *RemoveOrganizationAdminDeputyRequest, opts ...grpc.CallOption) (*RemoveOrganizationAdminDeputyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveOrganizationAdminDeputyResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_RemoveOrganizationAdminDeputy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) AssignOrganizationHead(ctx context.Context, in *AssignOrganizationHeadRequest, opts ...grpc.CallOption) (*AssignOrganizationHeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignOrganizationHeadResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_AssignOrganizationHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) RevokeOrganizationHead(ctx context.Context, in *RevokeOrganizationHeadRequest, opts ...grpc.CallOption) (*RevokeOrganizationHeadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeOrganizationHeadResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_RevokeOrganizationHead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) AssignOrganizationHeadDeputy(ctx context.Context, in *AssignOrganizationHeadDeputyRequest, opts ...grpc.CallOption) (*AssignOrganizationHeadDeputyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignOrganizationHeadDeputyResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_AssignOrganizationHeadDeputy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) RemoveOrganizationHeadDeputy(ctx context.Context, in *RemoveOrganizationHeadDeputyRequest, opts ...grpc.CallOption) (*RemoveOrganizationHeadDeputyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveOrganizationHeadDeputyResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_RemoveOrganizationHeadDeputy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) AssignOrganizationDispatcher(ctx context.Context, in *AssignOrganizationDispatcherRequest, opts ...grpc.CallOption) (*AssignOrganizationDispatcherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignOrganizationDispatcherResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_AssignOrganizationDispatcher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) RevokeOrganizationDispatcher(ctx context.Context, in *RevokeOrganizationDispatcherRequest, opts ...grpc.CallOption) (*RevokeOrganizationDispatcherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeOrganizationDispatcherResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_RevokeOrganizationDispatcher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) AssignOrganizationDispatcherDeputy(ctx context.Context, in *AssignOrganizationDispatcherDeputyRequest, opts ...grpc.CallOption) (*AssignOrganizationDispatcherDeputyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignOrganizationDispatcherDeputyResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_AssignOrganizationDispatcherDeputy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) RemoveOrganizationDispatcherDeputy(ctx context.Context, in *RemoveOrganizationDispatcherDeputyRequest, opts ...grpc.CallOption) (*RemoveOrganizationDispatcherDeputyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveOrganizationDispatcherDeputyResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_RemoveOrganizationDispatcherDeputy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) GrantSystemAdmin(ctx context.Context, in *GrantSystemAdminRequest, opts ...grpc.CallOption) (*GrantSystemAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantSystemAdminResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_GrantSystemAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membershipCommandServiceClient) RevokeSystemAdmin(ctx context.Context, in *RevokeSystemAdminRequest, opts ...grpc.CallOption) (*RevokeSystemAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeSystemAdminResponse)
	err := c.cc.Invoke(ctx, MembershipCommandService_RevokeSystemAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembershipCommandServiceServer is the server API for MembershipCommandService service.
// All implementations must embed UnimplementedMembershipCommandServiceServer
// for forward compatibility.
//
// MembershipService is the command-side contract for who-works-where
// data. It covers the Employee lifecycle (hire / update / terminate),
// Vacation lifecycle (start / schedule / end / cancel / change),
// role grants with deputy management for DepartmentResponsible,
// ClinicHead, OrganizationAdmin, OrganizationHead, and
// OrganizationDispatcher, plus the global SystemAdmin grant that
// operates directly on Zitadel user identifiers.
type MembershipCommandServiceServer interface {
	// Employee lifecycle
	HireEmployee(context.Context, *HireEmployeeRequest) (*HireEmployeeResponse, error)
	UpdateEmployeePosition(context.Context, *UpdateEmployeePositionRequest) (*UpdateEmployeePositionResponse, error)
	UpdateEmployeeDepartment(context.Context, *UpdateEmployeeDepartmentRequest) (*UpdateEmployeeDepartmentResponse, error)
	TerminateEmployee(context.Context, *TerminateEmployeeRequest) (*TerminateEmployeeResponse, error)
	DeactivateEmployee(context.Context, *DeactivateEmployeeRequest) (*DeactivateEmployeeResponse, error)
	ActivateEmployee(context.Context, *ActivateEmployeeRequest) (*ActivateEmployeeResponse, error)
	// Vacation lifecycle
	StartVacationNow(context.Context, *StartVacationNowRequest) (*StartVacationNowResponse, error)
	ScheduleVacation(context.Context, *ScheduleVacationRequest) (*ScheduleVacationResponse, error)
	UpdateVacationEndDate(context.Context, *UpdateVacationEndDateRequest) (*UpdateVacationEndDateResponse, error)
	ForceEndVacation(context.Context, *ForceEndVacationRequest) (*ForceEndVacationResponse, error)
	CancelScheduledVacation(context.Context, *CancelScheduledVacationRequest) (*CancelScheduledVacationResponse, error)
	// ------ DepartmentResponsible ------
	AssignDepartmentResponsible(context.Context, *AssignDepartmentResponsibleRequest) (*AssignDepartmentResponsibleResponse, error)
	RevokeDepartmentResponsible(context.Context, *RevokeDepartmentResponsibleRequest) (*RevokeDepartmentResponsibleResponse, error)
	AssignDepartmentResponsibleDeputy(context.Context, *AssignDepartmentResponsibleDeputyRequest) (*AssignDepartmentResponsibleDeputyResponse, error)
	RemoveDepartmentResponsibleDeputy(context.Context, *RemoveDepartmentResponsibleDeputyRequest) (*RemoveDepartmentResponsibleDeputyResponse, error)
	// ------ ClinicHead ------
	AssignClinicHead(context.Context, *AssignClinicHeadRequest) (*AssignClinicHeadResponse, error)
	RevokeClinicHead(context.Context, *RevokeClinicHeadRequest) (*RevokeClinicHeadResponse, error)
	AssignClinicHeadDeputy(context.Context, *AssignClinicHeadDeputyRequest) (*AssignClinicHeadDeputyResponse, error)
	RemoveClinicHeadDeputy(context.Context, *RemoveClinicHeadDeputyRequest) (*RemoveClinicHeadDeputyResponse, error)
	// ------ OrganizationAdmin ------
	AssignOrganizationAdmin(context.Context, *AssignOrganizationAdminRequest) (*AssignOrganizationAdminResponse, error)
	RevokeOrganizationAdmin(context.Context, *RevokeOrganizationAdminRequest) (*RevokeOrganizationAdminResponse, error)
	AssignOrganizationAdminDeputy(context.Context, *AssignOrganizationAdminDeputyRequest) (*AssignOrganizationAdminDeputyResponse, error)
	RemoveOrganizationAdminDeputy(context.Context, *RemoveOrganizationAdminDeputyRequest) (*RemoveOrganizationAdminDeputyResponse, error)
	// ------ OrganizationHead ------
	AssignOrganizationHead(context.Context, *AssignOrganizationHeadRequest) (*AssignOrganizationHeadResponse, error)
	RevokeOrganizationHead(context.Context, *RevokeOrganizationHeadRequest) (*RevokeOrganizationHeadResponse, error)
	AssignOrganizationHeadDeputy(context.Context, *AssignOrganizationHeadDeputyRequest) (*AssignOrganizationHeadDeputyResponse, error)
	RemoveOrganizationHeadDeputy(context.Context, *RemoveOrganizationHeadDeputyRequest) (*RemoveOrganizationHeadDeputyResponse, error)
	// ------ OrganizationDispatcher ------
	AssignOrganizationDispatcher(context.Context, *AssignOrganizationDispatcherRequest) (*AssignOrganizationDispatcherResponse, error)
	RevokeOrganizationDispatcher(context.Context, *RevokeOrganizationDispatcherRequest) (*RevokeOrganizationDispatcherResponse, error)
	AssignOrganizationDispatcherDeputy(context.Context, *AssignOrganizationDispatcherDeputyRequest) (*AssignOrganizationDispatcherDeputyResponse, error)
	RemoveOrganizationDispatcherDeputy(context.Context, *RemoveOrganizationDispatcherDeputyRequest) (*RemoveOrganizationDispatcherDeputyResponse, error)
	// ------ SystemAdmin ------
	GrantSystemAdmin(context.Context, *GrantSystemAdminRequest) (*GrantSystemAdminResponse, error)
	RevokeSystemAdmin(context.Context, *RevokeSystemAdminRequest) (*RevokeSystemAdminResponse, error)
	mustEmbedUnimplementedMembershipCommandServiceServer()
}

// UnimplementedMembershipCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMembershipCommandServiceServer struct{}

func (UnimplementedMembershipCommandServiceServer) HireEmployee(context.Context, *HireEmployeeRequest) (*HireEmployeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HireEmployee not implemented")
}
func (UnimplementedMembershipCommandServiceServer) UpdateEmployeePosition(context.Context, *UpdateEmployeePositionRequest) (*UpdateEmployeePositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEmployeePosition not implemented")
}
func (UnimplementedMembershipCommandServiceServer) UpdateEmployeeDepartment(context.Context, *UpdateEmployeeDepartmentRequest) (*UpdateEmployeeDepartmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEmployeeDepartment not implemented")
}
func (UnimplementedMembershipCommandServiceServer) TerminateEmployee(context.Context, *TerminateEmployeeRequest) (*TerminateEmployeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateEmployee not implemented")
}
func (UnimplementedMembershipCommandServiceServer) DeactivateEmployee(context.Context, *DeactivateEmployeeRequest) (*DeactivateEmployeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateEmployee not implemented")
}
func (UnimplementedMembershipCommandServiceServer) ActivateEmployee(context.Context, *ActivateEmployeeRequest) (*ActivateEmployeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateEmployee not implemented")
}
func (UnimplementedMembershipCommandServiceServer) StartVacationNow(context.Context, *StartVacationNowRequest) (*StartVacationNowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVacationNow not implemented")
}
func (UnimplementedMembershipCommandServiceServer) ScheduleVacation(context.Context, *ScheduleVacationRequest) (*ScheduleVacationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScheduleVacation not implemented")
}
func (UnimplementedMembershipCommandServiceServer) UpdateVacationEndDate(context.Context, *UpdateVacationEndDateRequest) (*UpdateVacationEndDateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVacationEndDate not implemented")
}
func (UnimplementedMembershipCommandServiceServer) ForceEndVacation(context.Context, *ForceEndVacationRequest) (*ForceEndVacationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceEndVacation not implemented")
}
func (UnimplementedMembershipCommandServiceServer) CancelScheduledVacation(context.Context, *CancelScheduledVacationRequest) (*CancelScheduledVacationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelScheduledVacation not implemented")
}
func (UnimplementedMembershipCommandServiceServer) AssignDepartmentResponsible(context.Context, *AssignDepartmentResponsibleRequest) (*AssignDepartmentResponsibleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignDepartmentResponsible not implemented")
}
func (UnimplementedMembershipCommandServiceServer) RevokeDepartmentResponsible(context.Context, *RevokeDepartmentResponsibleRequest) (*RevokeDepartmentResponsibleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeDepartmentResponsible not implemented")
}
func (UnimplementedMembershipCommandServiceServer) AssignDepartmentResponsibleDeputy(context.Context, *AssignDepartmentResponsibleDeputyRequest) (*AssignDepartmentResponsibleDeputyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignDepartmentResponsibleDeputy not implemented")
}
func (UnimplementedMembershipCommandServiceServer) RemoveDepartmentResponsibleDeputy(context.Context, *RemoveDepartmentResponsibleDeputyRequest) (*RemoveDepartmentResponsibleDeputyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveDepartmentResponsibleDeputy not implemented")
}
func (UnimplementedMembershipCommandServiceServer) AssignClinicHead(context.Context, *AssignClinicHeadRequest) (*AssignClinicHeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignClinicHead not implemented")
}
func (UnimplementedMembershipCommandServiceServer) RevokeClinicHead(context.Context, *RevokeClinicHeadRequest) (*RevokeClinicHeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeClinicHead not implemented")
}
func (UnimplementedMembershipCommandServiceServer) AssignClinicHeadDeputy(context.Context, *AssignClinicHeadDeputyRequest) (*AssignClinicHeadDeputyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignClinicHeadDeputy not implemented")
}
func (UnimplementedMembershipCommandServiceServer) RemoveClinicHeadDeputy(context.Context, *RemoveClinicHeadDeputyRequest) (*RemoveClinicHeadDeputyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveClinicHeadDeputy not implemented")
}
func (UnimplementedMembershipCommandServiceServer) AssignOrganizationAdmin(context.Context, *AssignOrganizationAdminRequest) (*AssignOrganizationAdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignOrganizationAdmin not implemented")
}
func (UnimplementedMembershipCommandServiceServer) RevokeOrganizationAdmin(context.Context, *RevokeOrganizationAdminRequest) (*RevokeOrganizationAdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeOrganizationAdmin not implemented")
}
func (UnimplementedMembershipCommandServiceServer) AssignOrganizationAdminDeputy(context.Context, *AssignOrganizationAdminDeputyRequest) (*AssignOrganizationAdminDeputyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignOrganizationAdminDeputy not implemented")
}
func (UnimplementedMembershipCommandServiceServer) RemoveOrganizationAdminDeputy(context.Context, *RemoveOrganizationAdminDeputyRequest) (*RemoveOrganizationAdminDeputyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveOrganizationAdminDeputy not implemented")
}
func (UnimplementedMembershipCommandServiceServer) AssignOrganizationHead(context.Context, *AssignOrganizationHeadRequest) (*AssignOrganizationHeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignOrganizationHead not implemented")
}
func (UnimplementedMembershipCommandServiceServer) RevokeOrganizationHead(context.Context, *RevokeOrganizationHeadRequest) (*RevokeOrganizationHeadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeOrganizationHead not implemented")
}
func (UnimplementedMembershipCommandServiceServer) AssignOrganizationHeadDeputy(context.Context, *AssignOrganizationHeadDeputyRequest) (*AssignOrganizationHeadDeputyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignOrganizationHeadDeputy not implemented")
}
func (UnimplementedMembershipCommandServiceServer) RemoveOrganizationHeadDeputy(context.Context, *RemoveOrganizationHeadDeputyRequest) (*RemoveOrganizationHeadDeputyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveOrganizationHeadDeputy not implemented")
}
func (UnimplementedMembershipCommandServiceServer) AssignOrganizationDispatcher(context.Context, *AssignOrganizationDispatcherRequest) (*AssignOrganizationDispatcherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignOrganizationDispatcher not implemented")
}
func (UnimplementedMembershipCommandServiceServer) RevokeOrganizationDispatcher(context.Context, *RevokeOrganizationDispatcherRequest) (*RevokeOrganizationDispatcherResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeOrganizationDispatcher not implemented")
}
func (UnimplementedMembershipCommandServiceServer) AssignOrganizationDispatcherDeputy(context.Context, *AssignOrganizationDispatcherDeputyRequest) (*AssignOrganizationDispatcherDeputyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignOrganizationDispatcherDeputy not implemented")
}
func (UnimplementedMembershipCommandServiceServer) RemoveOrganizationDispatcherDeputy(context.Context, *RemoveOrganizationDispatcherDeputyRequest) (*RemoveOrganizationDispatcherDeputyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveOrganizationDispatcherDeputy not implemented")
}
func (UnimplementedMembershipCommandServiceServer) GrantSystemAdmin(context.Context, *GrantSystemAdminRequest) (*GrantSystemAdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantSystemAdmin not implemented")
}
func (UnimplementedMembershipCommandServiceServer) RevokeSystemAdmin(context.Context, *RevokeSystemAdminRequest) (*RevokeSystemAdminResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeSystemAdmin not implemented")
}
func (UnimplementedMembershipCommandServiceServer) mustEmbedUnimplementedMembershipCommandServiceServer() {
}
func (UnimplementedMembershipCommandServiceServer) testEmbeddedByValue() {}

// UnsafeMembershipCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembershipCommandServiceServer will
// result in compilation errors.
type UnsafeMembershipCommandServiceServer interface {
	mustEmbedUnimplementedMembershipCommandServiceServer()
}

func RegisterMembershipCommandServiceServer(s grpc.ServiceRegistrar, srv MembershipCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedMembershipCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MembershipCommandService_ServiceDesc, srv)
}

func _MembershipCommandService_HireEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HireEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).HireEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_HireEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).HireEmployee(ctx, req.(*HireEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_UpdateEmployeePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmployeePositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).UpdateEmployeePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_UpdateEmployeePosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).UpdateEmployeePosition(ctx, req.(*UpdateEmployeePositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_UpdateEmployeeDepartment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmployeeDepartmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).UpdateEmployeeDepartment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_UpdateEmployeeDepartment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).UpdateEmployeeDepartment(ctx, req.(*UpdateEmployeeDepartmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_TerminateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).TerminateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_TerminateEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).TerminateEmployee(ctx, req.(*TerminateEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_DeactivateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).DeactivateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_DeactivateEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).DeactivateEmployee(ctx, req.(*DeactivateEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_ActivateEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateEmployeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).ActivateEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_ActivateEmployee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).ActivateEmployee(ctx, req.(*ActivateEmployeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_StartVacationNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVacationNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).StartVacationNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_StartVacationNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).StartVacationNow(ctx, req.(*StartVacationNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_ScheduleVacation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleVacationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).ScheduleVacation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_ScheduleVacation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).ScheduleVacation(ctx, req.(*ScheduleVacationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_UpdateVacationEndDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVacationEndDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).UpdateVacationEndDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_UpdateVacationEndDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).UpdateVacationEndDate(ctx, req.(*UpdateVacationEndDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_ForceEndVacation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceEndVacationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).ForceEndVacation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_ForceEndVacation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).ForceEndVacation(ctx, req.(*ForceEndVacationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_CancelScheduledVacation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelScheduledVacationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).CancelScheduledVacation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_CancelScheduledVacation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).CancelScheduledVacation(ctx, req.(*CancelScheduledVacationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_AssignDepartmentResponsible_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignDepartmentResponsibleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).AssignDepartmentResponsible(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_AssignDepartmentResponsible_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).AssignDepartmentResponsible(ctx, req.(*AssignDepartmentResponsibleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_RevokeDepartmentResponsible_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDepartmentResponsibleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).RevokeDepartmentResponsible(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_RevokeDepartmentResponsible_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).RevokeDepartmentResponsible(ctx, req.(*RevokeDepartmentResponsibleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_AssignDepartmentResponsibleDeputy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignDepartmentResponsibleDeputyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).AssignDepartmentResponsibleDeputy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_AssignDepartmentResponsibleDeputy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).AssignDepartmentResponsibleDeputy(ctx, req.(*AssignDepartmentResponsibleDeputyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_RemoveDepartmentResponsibleDeputy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveDepartmentResponsibleDeputyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).RemoveDepartmentResponsibleDeputy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_RemoveDepartmentResponsibleDeputy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).RemoveDepartmentResponsibleDeputy(ctx, req.(*RemoveDepartmentResponsibleDeputyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_AssignClinicHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignClinicHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).AssignClinicHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_AssignClinicHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).AssignClinicHead(ctx, req.(*AssignClinicHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_RevokeClinicHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeClinicHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).RevokeClinicHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_RevokeClinicHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).RevokeClinicHead(ctx, req.(*RevokeClinicHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_AssignClinicHeadDeputy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignClinicHeadDeputyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).AssignClinicHeadDeputy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_AssignClinicHeadDeputy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).AssignClinicHeadDeputy(ctx, req.(*AssignClinicHeadDeputyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_RemoveClinicHeadDeputy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveClinicHeadDeputyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).RemoveClinicHeadDeputy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_RemoveClinicHeadDeputy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).RemoveClinicHeadDeputy(ctx, req.(*RemoveClinicHeadDeputyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_AssignOrganizationAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignOrganizationAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).AssignOrganizationAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_AssignOrganizationAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).AssignOrganizationAdmin(ctx, req.(*AssignOrganizationAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_RevokeOrganizationAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeOrganizationAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).RevokeOrganizationAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_RevokeOrganizationAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).RevokeOrganizationAdmin(ctx, req.(*RevokeOrganizationAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_AssignOrganizationAdminDeputy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignOrganizationAdminDeputyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).AssignOrganizationAdminDeputy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_AssignOrganizationAdminDeputy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).AssignOrganizationAdminDeputy(ctx, req.(*AssignOrganizationAdminDeputyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_RemoveOrganizationAdminDeputy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOrganizationAdminDeputyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).RemoveOrganizationAdminDeputy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_RemoveOrganizationAdminDeputy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).RemoveOrganizationAdminDeputy(ctx, req.(*RemoveOrganizationAdminDeputyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_AssignOrganizationHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignOrganizationHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).AssignOrganizationHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_AssignOrganizationHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).AssignOrganizationHead(ctx, req.(*AssignOrganizationHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_RevokeOrganizationHead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeOrganizationHeadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).RevokeOrganizationHead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_RevokeOrganizationHead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).RevokeOrganizationHead(ctx, req.(*RevokeOrganizationHeadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_AssignOrganizationHeadDeputy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignOrganizationHeadDeputyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).AssignOrganizationHeadDeputy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_AssignOrganizationHeadDeputy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).AssignOrganizationHeadDeputy(ctx, req.(*AssignOrganizationHeadDeputyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_RemoveOrganizationHeadDeputy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOrganizationHeadDeputyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).RemoveOrganizationHeadDeputy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_RemoveOrganizationHeadDeputy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).RemoveOrganizationHeadDeputy(ctx, req.(*RemoveOrganizationHeadDeputyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_AssignOrganizationDispatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignOrganizationDispatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).AssignOrganizationDispatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_AssignOrganizationDispatcher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).AssignOrganizationDispatcher(ctx, req.(*AssignOrganizationDispatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_RevokeOrganizationDispatcher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeOrganizationDispatcherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).RevokeOrganizationDispatcher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_RevokeOrganizationDispatcher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).RevokeOrganizationDispatcher(ctx, req.(*RevokeOrganizationDispatcherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_AssignOrganizationDispatcherDeputy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignOrganizationDispatcherDeputyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).AssignOrganizationDispatcherDeputy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_AssignOrganizationDispatcherDeputy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).AssignOrganizationDispatcherDeputy(ctx, req.(*AssignOrganizationDispatcherDeputyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_RemoveOrganizationDispatcherDeputy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOrganizationDispatcherDeputyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).RemoveOrganizationDispatcherDeputy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_RemoveOrganizationDispatcherDeputy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).RemoveOrganizationDispatcherDeputy(ctx, req.(*RemoveOrganizationDispatcherDeputyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_GrantSystemAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantSystemAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).GrantSystemAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_GrantSystemAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).GrantSystemAdmin(ctx, req.(*GrantSystemAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MembershipCommandService_RevokeSystemAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeSystemAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembershipCommandServiceServer).RevokeSystemAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MembershipCommandService_RevokeSystemAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembershipCommandServiceServer).RevokeSystemAdmin(ctx, req.(*RevokeSystemAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MembershipCommandService_ServiceDesc is the grpc.ServiceDesc for MembershipCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MembershipCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "command.membership.v1.MembershipCommandService",
	HandlerType: (*MembershipCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HireEmployee",
			Handler:    _MembershipCommandService_HireEmployee_Handler,
		},
		{
			MethodName: "UpdateEmployeePosition",
			Handler:    _MembershipCommandService_UpdateEmployeePosition_Handler,
		},
		{
			MethodName: "UpdateEmployeeDepartment",
			Handler:    _MembershipCommandService_UpdateEmployeeDepartment_Handler,
		},
		{
			MethodName: "TerminateEmployee",
			Handler:    _MembershipCommandService_TerminateEmployee_Handler,
		},
		{
			MethodName: "DeactivateEmployee",
			Handler:    _MembershipCommandService_DeactivateEmployee_Handler,
		},
		{
			MethodName: "ActivateEmployee",
			Handler:    _MembershipCommandService_ActivateEmployee_Handler,
		},
		{
			MethodName: "StartVacationNow",
			Handler:    _MembershipCommandService_StartVacationNow_Handler,
		},
		{
			MethodName: "ScheduleVacation",
			Handler:    _MembershipCommandService_ScheduleVacation_Handler,
		},
		{
			MethodName: "UpdateVacationEndDate",
			Handler:    _MembershipCommandService_UpdateVacationEndDate_Handler,
		},
		{
			MethodName: "ForceEndVacation",
			Handler:    _MembershipCommandService_ForceEndVacation_Handler,
		},
		{
			MethodName: "CancelScheduledVacation",
			Handler:    _MembershipCommandService_CancelScheduledVacation_Handler,
		},
		{
			MethodName: "AssignDepartmentResponsible",
			Handler:    _MembershipCommandService_AssignDepartmentResponsible_Handler,
		},
		{
			MethodName: "RevokeDepartmentResponsible",
			Handler:    _MembershipCommandService_RevokeDepartmentResponsible_Handler,
		},
		{
			MethodName: "AssignDepartmentResponsibleDeputy",
			Handler:    _MembershipCommandService_AssignDepartmentResponsibleDeputy_Handler,
		},
		{
			MethodName: "RemoveDepartmentResponsibleDeputy",
			Handler:    _MembershipCommandService_RemoveDepartmentResponsibleDeputy_Handler,
		},
		{
			MethodName: "AssignClinicHead",
			Handler:    _MembershipCommandService_AssignClinicHead_Handler,
		},
		{
			MethodName: "RevokeClinicHead",
			Handler:    _MembershipCommandService_RevokeClinicHead_Handler,
		},
		{
			MethodName: "AssignClinicHeadDeputy",
			Handler:    _MembershipCommandService_AssignClinicHeadDeputy_Handler,
		},
		{
			MethodName: "RemoveClinicHeadDeputy",
			Handler:    _MembershipCommandService_RemoveClinicHeadDeputy_Handler,
		},
		{
			MethodName: "AssignOrganizationAdmin",
			Handler:    _MembershipCommandService_AssignOrganizationAdmin_Handler,
		},
		{
			MethodName: "RevokeOrganizationAdmin",
			Handler:    _MembershipCommandService_RevokeOrganizationAdmin_Handler,
		},
		{
			MethodName: "AssignOrganizationAdminDeputy",
			Handler:    _MembershipCommandService_AssignOrganizationAdminDeputy_Handler,
		},
		{
			MethodName: "RemoveOrganizationAdminDeputy",
			Handler:    _MembershipCommandService_RemoveOrganizationAdminDeputy_Handler,
		},
		{
			MethodName: "AssignOrganizationHead",
			Handler:    _MembershipCommandService_AssignOrganizationHead_Handler,
		},
		{
			MethodName: "RevokeOrganizationHead",
			Handler:    _MembershipCommandService_RevokeOrganizationHead_Handler,
		},
		{
			MethodName: "AssignOrganizationHeadDeputy",
			Handler:    _MembershipCommandService_AssignOrganizationHeadDeputy_Handler,
		},
		{
			MethodName: "RemoveOrganizationHeadDeputy",
			Handler:    _MembershipCommandService_RemoveOrganizationHeadDeputy_Handler,
		},
		{
			MethodName: "AssignOrganizationDispatcher",
			Handler:    _MembershipCommandService_AssignOrganizationDispatcher_Handler,
		},
		{
			MethodName: "RevokeOrganizationDispatcher",
			Handler:    _MembershipCommandService_RevokeOrganizationDispatcher_Handler,
		},
		{
			MethodName: "AssignOrganizationDispatcherDeputy",
			Handler:    _MembershipCommandService_AssignOrganizationDispatcherDeputy_Handler,
		},
		{
			MethodName: "RemoveOrganizationDispatcherDeputy",
			Handler:    _MembershipCommandService_RemoveOrganizationDispatcherDeputy_Handler,
		},
		{
			MethodName: "GrantSystemAdmin",
			Handler:    _MembershipCommandService_GrantSystemAdmin_Handler,
		},
		{
			MethodName: "RevokeSystemAdmin",
			Handler:    _MembershipCommandService_RevokeSystemAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "command/membership/v1/membership.proto",
}
