// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: command/request/classifier/v1/request_classifier.proto

package classifierv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RequestClassifierCommandService_CreateRequestType_FullMethodName        = "/command.request.classifier.v1.RequestClassifierCommandService/CreateRequestType"
	RequestClassifierCommandService_UpdateRequestTypeDetails_FullMethodName = "/command.request.classifier.v1.RequestClassifierCommandService/UpdateRequestTypeDetails"
	RequestClassifierCommandService_DeactivateRequestType_FullMethodName    = "/command.request.classifier.v1.RequestClassifierCommandService/DeactivateRequestType"
	RequestClassifierCommandService_ReactivateRequestType_FullMethodName    = "/command.request.classifier.v1.RequestClassifierCommandService/ReactivateRequestType"
	RequestClassifierCommandService_DeleteRequestType_FullMethodName        = "/command.request.classifier.v1.RequestClassifierCommandService/DeleteRequestType"
)

// RequestClassifierCommandServiceClient is the client API for RequestClassifierCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RequestClassifierCommandServiceClient interface {
	CreateRequestType(ctx context.Context, in *CreateRequestTypeRequest, opts ...grpc.CallOption) (*CreateRequestTypeResponse, error)
	UpdateRequestTypeDetails(ctx context.Context, in *UpdateRequestTypeDetailsRequest, opts ...grpc.CallOption) (*UpdateRequestTypeDetailsResponse, error)
	DeactivateRequestType(ctx context.Context, in *DeactivateRequestTypeRequest, opts ...grpc.CallOption) (*DeactivateRequestTypeResponse, error)
	ReactivateRequestType(ctx context.Context, in *ReactivateRequestTypeRequest, opts ...grpc.CallOption) (*ReactivateRequestTypeResponse, error)
	DeleteRequestType(ctx context.Context, in *DeleteRequestTypeRequest, opts ...grpc.CallOption) (*DeleteRequestTypeResponse, error)
}

type requestClassifierCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRequestClassifierCommandServiceClient(cc grpc.ClientConnInterface) RequestClassifierCommandServiceClient {
	return &requestClassifierCommandServiceClient{cc}
}

func (c *requestClassifierCommandServiceClient) CreateRequestType(ctx context.Context, in *CreateRequestTypeRequest, opts ...grpc.CallOption) (*CreateRequestTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRequestTypeResponse)
	err := c.cc.Invoke(ctx, RequestClassifierCommandService_CreateRequestType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestClassifierCommandServiceClient) UpdateRequestTypeDetails(ctx context.Context, in *UpdateRequestTypeDetailsRequest, opts ...grpc.CallOption) (*UpdateRequestTypeDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRequestTypeDetailsResponse)
	err := c.cc.Invoke(ctx, RequestClassifierCommandService_UpdateRequestTypeDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestClassifierCommandServiceClient) DeactivateRequestType(ctx context.Context, in *DeactivateRequestTypeRequest, opts ...grpc.CallOption) (*DeactivateRequestTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateRequestTypeResponse)
	err := c.cc.Invoke(ctx, RequestClassifierCommandService_DeactivateRequestType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestClassifierCommandServiceClient) ReactivateRequestType(ctx context.Context, in *ReactivateRequestTypeRequest, opts ...grpc.CallOption) (*ReactivateRequestTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReactivateRequestTypeResponse)
	err := c.cc.Invoke(ctx, RequestClassifierCommandService_ReactivateRequestType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *requestClassifierCommandServiceClient) DeleteRequestType(ctx context.Context, in *DeleteRequestTypeRequest, opts ...grpc.CallOption) (*DeleteRequestTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRequestTypeResponse)
	err := c.cc.Invoke(ctx, RequestClassifierCommandService_DeleteRequestType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RequestClassifierCommandServiceServer is the server API for RequestClassifierCommandService service.
// All implementations must embed UnimplementedRequestClassifierCommandServiceServer
// for forward compatibility.
type RequestClassifierCommandServiceServer interface {
	CreateRequestType(context.Context, *CreateRequestTypeRequest) (*CreateRequestTypeResponse, error)
	UpdateRequestTypeDetails(context.Context, *UpdateRequestTypeDetailsRequest) (*UpdateRequestTypeDetailsResponse, error)
	DeactivateRequestType(context.Context, *DeactivateRequestTypeRequest) (*DeactivateRequestTypeResponse, error)
	ReactivateRequestType(context.Context, *ReactivateRequestTypeRequest) (*ReactivateRequestTypeResponse, error)
	DeleteRequestType(context.Context, *DeleteRequestTypeRequest) (*DeleteRequestTypeResponse, error)
	mustEmbedUnimplementedRequestClassifierCommandServiceServer()
}

// UnimplementedRequestClassifierCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRequestClassifierCommandServiceServer struct{}

func (UnimplementedRequestClassifierCommandServiceServer) CreateRequestType(context.Context, *CreateRequestTypeRequest) (*CreateRequestTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRequestType not implemented")
}
func (UnimplementedRequestClassifierCommandServiceServer) UpdateRequestTypeDetails(context.Context, *UpdateRequestTypeDetailsRequest) (*UpdateRequestTypeDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRequestTypeDetails not implemented")
}
func (UnimplementedRequestClassifierCommandServiceServer) DeactivateRequestType(context.Context, *DeactivateRequestTypeRequest) (*DeactivateRequestTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeactivateRequestType not implemented")
}
func (UnimplementedRequestClassifierCommandServiceServer) ReactivateRequestType(context.Context, *ReactivateRequestTypeRequest) (*ReactivateRequestTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReactivateRequestType not implemented")
}
func (UnimplementedRequestClassifierCommandServiceServer) DeleteRequestType(context.Context, *DeleteRequestTypeRequest) (*DeleteRequestTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRequestType not implemented")
}
func (UnimplementedRequestClassifierCommandServiceServer) mustEmbedUnimplementedRequestClassifierCommandServiceServer() {
}
func (UnimplementedRequestClassifierCommandServiceServer) testEmbeddedByValue() {}

// UnsafeRequestClassifierCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RequestClassifierCommandServiceServer will
// result in compilation errors.
type UnsafeRequestClassifierCommandServiceServer interface {
	mustEmbedUnimplementedRequestClassifierCommandServiceServer()
}

func RegisterRequestClassifierCommandServiceServer(s grpc.ServiceRegistrar, srv RequestClassifierCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedRequestClassifierCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RequestClassifierCommandService_ServiceDesc, srv)
}

func _RequestClassifierCommandService_CreateRequestType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequestTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestClassifierCommandServiceServer).CreateRequestType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestClassifierCommandService_CreateRequestType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestClassifierCommandServiceServer).CreateRequestType(ctx, req.(*CreateRequestTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestClassifierCommandService_UpdateRequestTypeDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequestTypeDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestClassifierCommandServiceServer).UpdateRequestTypeDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestClassifierCommandService_UpdateRequestTypeDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestClassifierCommandServiceServer).UpdateRequestTypeDetails(ctx, req.(*UpdateRequestTypeDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestClassifierCommandService_DeactivateRequestType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateRequestTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestClassifierCommandServiceServer).DeactivateRequestType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestClassifierCommandService_DeactivateRequestType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestClassifierCommandServiceServer).DeactivateRequestType(ctx, req.(*DeactivateRequestTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestClassifierCommandService_ReactivateRequestType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactivateRequestTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestClassifierCommandServiceServer).ReactivateRequestType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestClassifierCommandService_ReactivateRequestType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestClassifierCommandServiceServer).ReactivateRequestType(ctx, req.(*ReactivateRequestTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RequestClassifierCommandService_DeleteRequestType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequestTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestClassifierCommandServiceServer).DeleteRequestType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RequestClassifierCommandService_DeleteRequestType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestClassifierCommandServiceServer).DeleteRequestType(ctx, req.(*DeleteRequestTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RequestClassifierCommandService_ServiceDesc is the grpc.ServiceDesc for RequestClassifierCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RequestClassifierCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "command.request.classifier.v1.RequestClassifierCommandService",
	HandlerType: (*RequestClassifierCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRequestType",
			Handler:    _RequestClassifierCommandService_CreateRequestType_Handler,
		},
		{
			MethodName: "UpdateRequestTypeDetails",
			Handler:    _RequestClassifierCommandService_UpdateRequestTypeDetails_Handler,
		},
		{
			MethodName: "DeactivateRequestType",
			Handler:    _RequestClassifierCommandService_DeactivateRequestType_Handler,
		},
		{
			MethodName: "ReactivateRequestType",
			Handler:    _RequestClassifierCommandService_ReactivateRequestType_Handler,
		},
		{
			MethodName: "DeleteRequestType",
			Handler:    _RequestClassifierCommandService_DeleteRequestType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "command/request/classifier/v1/request_classifier.proto",
}
