// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: query/incident/classifier/v1/classifier.proto

package classifierv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "github.com/medincident/medincident-backend/pkg/error/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Category mirrors projections.incident_categories row.
type Category struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId   string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	ParentCategoryId *string                `protobuf:"bytes,3,opt,name=parent_category_id,json=parentCategoryId,proto3,oneof" json:"parent_category_id,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description      *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IsActive         bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Category) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Category) GetParentCategoryId() string {
	if x != nil && x.ParentCategoryId != nil {
		return *x.ParentCategoryId
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Category) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Category) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Category) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// Type mirrors projections.incident_types row.
type Type struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrganizationId       string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	CategoryId           string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name                 string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IsActive             bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsAllowedForPatients bool                   `protobuf:"varint,9,opt,name=is_allowed_for_patients,json=isAllowedForPatients,proto3" json:"is_allowed_for_patients,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Type) Reset() {
	*x = Type{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{1}
}

func (x *Type) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Type) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Type) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Type) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Type) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Type) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Type) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Type) GetIsAllowedForPatients() bool {
	if x != nil {
		return x.IsAllowedForPatients
	}
	return false
}

type GetCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryRequest) Reset() {
	*x = GetCategoryRequest{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryRequest) ProtoMessage() {}

func (x *GetCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{2}
}

func (x *GetCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryResponse) Reset() {
	*x = GetCategoryResponse{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryResponse) ProtoMessage() {}

func (x *GetCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryResponse) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{3}
}

func (x *GetCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type ListCategoriesByOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListCategoriesByOrganizationRequest) Reset() {
	*x = ListCategoriesByOrganizationRequest{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesByOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesByOrganizationRequest) ProtoMessage() {}

func (x *ListCategoriesByOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesByOrganizationRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesByOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{4}
}

func (x *ListCategoriesByOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListCategoriesByOrganizationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCategoriesByOrganizationRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListCategoriesByOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Category            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesByOrganizationResponse) Reset() {
	*x = ListCategoriesByOrganizationResponse{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesByOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesByOrganizationResponse) ProtoMessage() {}

func (x *ListCategoriesByOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesByOrganizationResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesByOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{5}
}

func (x *ListCategoriesByOrganizationResponse) GetItems() []*Category {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListActiveRootCategoriesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListActiveRootCategoriesRequest) Reset() {
	*x = ListActiveRootCategoriesRequest{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveRootCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveRootCategoriesRequest) ProtoMessage() {}

func (x *ListActiveRootCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveRootCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListActiveRootCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{6}
}

func (x *ListActiveRootCategoriesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListActiveRootCategoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListActiveRootCategoriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListActiveRootCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Category            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveRootCategoriesResponse) Reset() {
	*x = ListActiveRootCategoriesResponse{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveRootCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveRootCategoriesResponse) ProtoMessage() {}

func (x *ListActiveRootCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveRootCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListActiveRootCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{7}
}

func (x *ListActiveRootCategoriesResponse) GetItems() []*Category {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListCategorySubtreeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RootCategoryId string                 `protobuf:"bytes,1,opt,name=root_category_id,json=rootCategoryId,proto3" json:"root_category_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListCategorySubtreeRequest) Reset() {
	*x = ListCategorySubtreeRequest{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategorySubtreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategorySubtreeRequest) ProtoMessage() {}

func (x *ListCategorySubtreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategorySubtreeRequest.ProtoReflect.Descriptor instead.
func (*ListCategorySubtreeRequest) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{8}
}

func (x *ListCategorySubtreeRequest) GetRootCategoryId() string {
	if x != nil {
		return x.RootCategoryId
	}
	return ""
}

type ListCategorySubtreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Category            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategorySubtreeResponse) Reset() {
	*x = ListCategorySubtreeResponse{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategorySubtreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategorySubtreeResponse) ProtoMessage() {}

func (x *ListCategorySubtreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategorySubtreeResponse.ProtoReflect.Descriptor instead.
func (*ListCategorySubtreeResponse) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{9}
}

func (x *ListCategorySubtreeResponse) GetItems() []*Category {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTypeRequest) Reset() {
	*x = GetTypeRequest{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeRequest) ProtoMessage() {}

func (x *GetTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeRequest.ProtoReflect.Descriptor instead.
func (*GetTypeRequest) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{10}
}

func (x *GetTypeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *Type                  `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTypeResponse) Reset() {
	*x = GetTypeResponse{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeResponse) ProtoMessage() {}

func (x *GetTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeResponse.ProtoReflect.Descriptor instead.
func (*GetTypeResponse) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{11}
}

func (x *GetTypeResponse) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

type ListTypesByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTypesByCategoryRequest) Reset() {
	*x = ListTypesByCategoryRequest{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypesByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypesByCategoryRequest) ProtoMessage() {}

func (x *ListTypesByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypesByCategoryRequest.ProtoReflect.Descriptor instead.
func (*ListTypesByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{12}
}

func (x *ListTypesByCategoryRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ListTypesByCategoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTypesByCategoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTypesByCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Type                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTypesByCategoryResponse) Reset() {
	*x = ListTypesByCategoryResponse{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTypesByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTypesByCategoryResponse) ProtoMessage() {}

func (x *ListTypesByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTypesByCategoryResponse.ProtoReflect.Descriptor instead.
func (*ListTypesByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{13}
}

func (x *ListTypesByCategoryResponse) GetItems() []*Type {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListActiveTypesByOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListActiveTypesByOrganizationRequest) Reset() {
	*x = ListActiveTypesByOrganizationRequest{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveTypesByOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveTypesByOrganizationRequest) ProtoMessage() {}

func (x *ListActiveTypesByOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveTypesByOrganizationRequest.ProtoReflect.Descriptor instead.
func (*ListActiveTypesByOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{14}
}

func (x *ListActiveTypesByOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListActiveTypesByOrganizationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListActiveTypesByOrganizationRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListActiveTypesByOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Type                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveTypesByOrganizationResponse) Reset() {
	*x = ListActiveTypesByOrganizationResponse{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveTypesByOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveTypesByOrganizationResponse) ProtoMessage() {}

func (x *ListActiveTypesByOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveTypesByOrganizationResponse.ProtoReflect.Descriptor instead.
func (*ListActiveTypesByOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{15}
}

func (x *ListActiveTypesByOrganizationResponse) GetItems() []*Type {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListPatientAllowedTypesByOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPatientAllowedTypesByOrganizationRequest) Reset() {
	*x = ListPatientAllowedTypesByOrganizationRequest{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientAllowedTypesByOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientAllowedTypesByOrganizationRequest) ProtoMessage() {}

func (x *ListPatientAllowedTypesByOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientAllowedTypesByOrganizationRequest.ProtoReflect.Descriptor instead.
func (*ListPatientAllowedTypesByOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{16}
}

func (x *ListPatientAllowedTypesByOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListPatientAllowedTypesByOrganizationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPatientAllowedTypesByOrganizationRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListPatientAllowedTypesByOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Type                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientAllowedTypesByOrganizationResponse) Reset() {
	*x = ListPatientAllowedTypesByOrganizationResponse{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientAllowedTypesByOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientAllowedTypesByOrganizationResponse) ProtoMessage() {}

func (x *ListPatientAllowedTypesByOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientAllowedTypesByOrganizationResponse.ProtoReflect.Descriptor instead.
func (*ListPatientAllowedTypesByOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{17}
}

func (x *ListPatientAllowedTypesByOrganizationResponse) GetItems() []*Type {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListPatientVisibleCategoriesByOrganizationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListPatientVisibleCategoriesByOrganizationRequest) Reset() {
	*x = ListPatientVisibleCategoriesByOrganizationRequest{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientVisibleCategoriesByOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientVisibleCategoriesByOrganizationRequest) ProtoMessage() {}

func (x *ListPatientVisibleCategoriesByOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientVisibleCategoriesByOrganizationRequest.ProtoReflect.Descriptor instead.
func (*ListPatientVisibleCategoriesByOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{18}
}

func (x *ListPatientVisibleCategoriesByOrganizationRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *ListPatientVisibleCategoriesByOrganizationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListPatientVisibleCategoriesByOrganizationRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListPatientVisibleCategoriesByOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Category            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPatientVisibleCategoriesByOrganizationResponse) Reset() {
	*x = ListPatientVisibleCategoriesByOrganizationResponse{}
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPatientVisibleCategoriesByOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPatientVisibleCategoriesByOrganizationResponse) ProtoMessage() {}

func (x *ListPatientVisibleCategoriesByOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_incident_classifier_v1_classifier_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPatientVisibleCategoriesByOrganizationResponse.ProtoReflect.Descriptor instead.
func (*ListPatientVisibleCategoriesByOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_query_incident_classifier_v1_classifier_proto_rawDescGZIP(), []int{19}
}

func (x *ListPatientVisibleCategoriesByOrganizationResponse) GetItems() []*Category {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_query_incident_classifier_v1_classifier_proto protoreflect.FileDescriptor

const file_query_incident_classifier_v1_classifier_proto_rawDesc = "" +
	"\n" +
	"-query/incident/classifier/v1/classifier.proto\x12\x1cquery.incident.classifier.v1\x1a\x14error/v1/error.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb3\x02\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x121\n" +
	"\x12parent_category_id\x18\x03 \x01(\tH\x00R\x10parentCategoryId\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAtB\x15\n" +
	"\x13_parent_category_idB\x0e\n" +
	"\f_description\"\xbd\x02\n" +
	"\x04Type\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x125\n" +
	"\x17is_allowed_for_patients\x18\t \x01(\bR\x14isAllowedForPatientsB\x0e\n" +
	"\f_description\"$\n" +
	"\x12GetCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x13GetCategoryResponse\x12B\n" +
	"\bcategory\x18\x01 \x01(\v2&.query.incident.classifier.v1.CategoryR\bcategory\"|\n" +
	"#ListCategoriesByOrganizationRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"d\n" +
	"$ListCategoriesByOrganizationResponse\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.query.incident.classifier.v1.CategoryR\x05items\"x\n" +
	"\x1fListActiveRootCategoriesRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"`\n" +
	" ListActiveRootCategoriesResponse\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.query.incident.classifier.v1.CategoryR\x05items\"F\n" +
	"\x1aListCategorySubtreeRequest\x12(\n" +
	"\x10root_category_id\x18\x01 \x01(\tR\x0erootCategoryId\"[\n" +
	"\x1bListCategorySubtreeResponse\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.query.incident.classifier.v1.CategoryR\x05items\" \n" +
	"\x0eGetTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"I\n" +
	"\x0fGetTypeResponse\x126\n" +
	"\x04type\x18\x01 \x01(\v2\".query.incident.classifier.v1.TypeR\x04type\"k\n" +
	"\x1aListTypesByCategoryRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"W\n" +
	"\x1bListTypesByCategoryResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".query.incident.classifier.v1.TypeR\x05items\"}\n" +
	"$ListActiveTypesByOrganizationRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"a\n" +
	"%ListActiveTypesByOrganizationResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".query.incident.classifier.v1.TypeR\x05items\"\x85\x01\n" +
	",ListPatientAllowedTypesByOrganizationRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"i\n" +
	"-ListPatientAllowedTypesByOrganizationResponse\x128\n" +
	"\x05items\x18\x01 \x03(\v2\".query.incident.classifier.v1.TypeR\x05items\"\x8a\x01\n" +
	"1ListPatientVisibleCategoriesByOrganizationRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"r\n" +
	"2ListPatientVisibleCategoriesByOrganizationResponse\x12<\n" +
	"\x05items\x18\x01 \x03(\v2&.query.incident.classifier.v1.CategoryR\x05items2\x8e\x13\n" +
	"\x1eIncidentClassifierQueryService\x12\x89\x03\n" +
	"\vGetCategory\x120.query.incident.classifier.v1.GetCategoryRequest\x1a1.query.incident.classifier.v1.GetCategoryResponse\"\x94\x02\x92A\xec\x01J\xe9\x01\n" +
	"\x03404\x12\xe1\x01\n" +
	"fNot found. Error codes:\n" +
	"- `incident_category_not_found` — category with the given ID does not exist.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponse\"Z\n" +
	"\x10application/json\x12F{\"code\":\"incident_category_not_found\",\"message\":\"Category not found.\"}\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/incident-categories/{id}\x12\xe6\x01\n" +
	"\x1cListCategoriesByOrganization\x12A.query.incident.classifier.v1.ListCategoriesByOrganizationRequest\x1aB.query.incident.classifier.v1.ListCategoriesByOrganizationResponse\"?\x82\xd3\xe4\x93\x029\x127/v1/organizations/{organization_id}/incident-categories\x12\xe0\x01\n" +
	"\x18ListActiveRootCategories\x12=.query.incident.classifier.v1.ListActiveRootCategoriesRequest\x1a>.query.incident.classifier.v1.ListActiveRootCategoriesResponse\"E\x82\xd3\xe4\x93\x02?\x12=/v1/organizations/{organization_id}/incident-categories:roots\x12\xc6\x01\n" +
	"\x13ListCategorySubtree\x128.query.incident.classifier.v1.ListCategorySubtreeRequest\x1a9.query.incident.classifier.v1.ListCategorySubtreeResponse\":\x82\xd3\xe4\x93\x024\x122/v1/incident-categories/{root_category_id}:subtree\x12\xe8\x02\n" +
	"\aGetType\x12,.query.incident.classifier.v1.GetTypeRequest\x1a-.query.incident.classifier.v1.GetTypeResponse\"\xff\x01\x92A\xdc\x01J\xd9\x01\n" +
	"\x03404\x12\xd1\x01\n" +
	"^Not found. Error codes:\n" +
	"- `incident_type_not_found` — type with the given ID does not exist.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponse\"R\n" +
	"\x10application/json\x12>{\"code\":\"incident_type_not_found\",\"message\":\"Type not found.\"}\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/incident-types/{id}\x12\xbf\x01\n" +
	"\x13ListTypesByCategory\x128.query.incident.classifier.v1.ListTypesByCategoryRequest\x1a9.query.incident.classifier.v1.ListTypesByCategoryResponse\"3\x82\xd3\xe4\x93\x02-\x12+/v1/incident-categories/{category_id}/types\x12\xeb\x01\n" +
	"\x1dListActiveTypesByOrganization\x12B.query.incident.classifier.v1.ListActiveTypesByOrganizationRequest\x1aC.query.incident.classifier.v1.ListActiveTypesByOrganizationResponse\"A\x82\xd3\xe4\x93\x02;\x129/v1/organizations/{organization_id}/incident-types:active\x12\x8c\x02\n" +
	"%ListPatientAllowedTypesByOrganization\x12J.query.incident.classifier.v1.ListPatientAllowedTypesByOrganizationRequest\x1aK.query.incident.classifier.v1.ListPatientAllowedTypesByOrganizationResponse\"J\x82\xd3\xe4\x93\x02D\x12B/v1/organizations/{organization_id}/incident-types:patient-allowed\x12\xa0\x02\n" +
	"*ListPatientVisibleCategoriesByOrganization\x12O.query.incident.classifier.v1.ListPatientVisibleCategoriesByOrganizationRequest\x1aP.query.incident.classifier.v1.ListPatientVisibleCategoriesByOrganizationResponse\"O\x82\xd3\xe4\x93\x02I\x12G/v1/organizations/{organization_id}/incident-categories:patient-visibleB\xbe\x04\x92A\x9a\x02RI\n" +
	"\x03400\x12B\n" +
	"#Validation failed or invalid input.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponseRS\n" +
	"\x03401\x12L\n" +
	"-Unauthenticated — missing or invalid token.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponseR8\n" +
	"\x03403\x121\n" +
	"\x12Permission denied.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponseR>\n" +
	"\x03500\x127\n" +
	"\x18Unexpected server error.\x12\x1b\n" +
	"\x19\x1a\x17.error.v1.ErrorResponse\n" +
	" com.query.incident.classifier.v1B\x0fClassifierProtoP\x01ZXgithub.com/medincident/medincident-backend/pkg/query/incident/classifier/v1;classifierv1\xa2\x02\x03QIC\xaa\x02\x1cQuery.Incident.Classifier.V1\xca\x02\x1cQuery\\Incident\\Classifier\\V1\xe2\x02(Query\\Incident\\Classifier\\V1\\GPBMetadata\xea\x02\x1fQuery::Incident::Classifier::V1b\x06proto3"

var (
	file_query_incident_classifier_v1_classifier_proto_rawDescOnce sync.Once
	file_query_incident_classifier_v1_classifier_proto_rawDescData []byte
)

func file_query_incident_classifier_v1_classifier_proto_rawDescGZIP() []byte {
	file_query_incident_classifier_v1_classifier_proto_rawDescOnce.Do(func() {
		file_query_incident_classifier_v1_classifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_incident_classifier_v1_classifier_proto_rawDesc), len(file_query_incident_classifier_v1_classifier_proto_rawDesc)))
	})
	return file_query_incident_classifier_v1_classifier_proto_rawDescData
}

var file_query_incident_classifier_v1_classifier_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_query_incident_classifier_v1_classifier_proto_goTypes = []any{
	(*Category)(nil),                                           // 0: query.incident.classifier.v1.Category
	(*Type)(nil),                                               // 1: query.incident.classifier.v1.Type
	(*GetCategoryRequest)(nil),                                 // 2: query.incident.classifier.v1.GetCategoryRequest
	(*GetCategoryResponse)(nil),                                // 3: query.incident.classifier.v1.GetCategoryResponse
	(*ListCategoriesByOrganizationRequest)(nil),                // 4: query.incident.classifier.v1.ListCategoriesByOrganizationRequest
	(*ListCategoriesByOrganizationResponse)(nil),               // 5: query.incident.classifier.v1.ListCategoriesByOrganizationResponse
	(*ListActiveRootCategoriesRequest)(nil),                    // 6: query.incident.classifier.v1.ListActiveRootCategoriesRequest
	(*ListActiveRootCategoriesResponse)(nil),                   // 7: query.incident.classifier.v1.ListActiveRootCategoriesResponse
	(*ListCategorySubtreeRequest)(nil),                         // 8: query.incident.classifier.v1.ListCategorySubtreeRequest
	(*ListCategorySubtreeResponse)(nil),                        // 9: query.incident.classifier.v1.ListCategorySubtreeResponse
	(*GetTypeRequest)(nil),                                     // 10: query.incident.classifier.v1.GetTypeRequest
	(*GetTypeResponse)(nil),                                    // 11: query.incident.classifier.v1.GetTypeResponse
	(*ListTypesByCategoryRequest)(nil),                         // 12: query.incident.classifier.v1.ListTypesByCategoryRequest
	(*ListTypesByCategoryResponse)(nil),                        // 13: query.incident.classifier.v1.ListTypesByCategoryResponse
	(*ListActiveTypesByOrganizationRequest)(nil),               // 14: query.incident.classifier.v1.ListActiveTypesByOrganizationRequest
	(*ListActiveTypesByOrganizationResponse)(nil),              // 15: query.incident.classifier.v1.ListActiveTypesByOrganizationResponse
	(*ListPatientAllowedTypesByOrganizationRequest)(nil),       // 16: query.incident.classifier.v1.ListPatientAllowedTypesByOrganizationRequest
	(*ListPatientAllowedTypesByOrganizationResponse)(nil),      // 17: query.incident.classifier.v1.ListPatientAllowedTypesByOrganizationResponse
	(*ListPatientVisibleCategoriesByOrganizationRequest)(nil),  // 18: query.incident.classifier.v1.ListPatientVisibleCategoriesByOrganizationRequest
	(*ListPatientVisibleCategoriesByOrganizationResponse)(nil), // 19: query.incident.classifier.v1.ListPatientVisibleCategoriesByOrganizationResponse
}
var file_query_incident_classifier_v1_classifier_proto_depIdxs = []int32{
	0,  // 0: query.incident.classifier.v1.GetCategoryResponse.category:type_name -> query.incident.classifier.v1.Category
	0,  // 1: query.incident.classifier.v1.ListCategoriesByOrganizationResponse.items:type_name -> query.incident.classifier.v1.Category
	0,  // 2: query.incident.classifier.v1.ListActiveRootCategoriesResponse.items:type_name -> query.incident.classifier.v1.Category
	0,  // 3: query.incident.classifier.v1.ListCategorySubtreeResponse.items:type_name -> query.incident.classifier.v1.Category
	1,  // 4: query.incident.classifier.v1.GetTypeResponse.type:type_name -> query.incident.classifier.v1.Type
	1,  // 5: query.incident.classifier.v1.ListTypesByCategoryResponse.items:type_name -> query.incident.classifier.v1.Type
	1,  // 6: query.incident.classifier.v1.ListActiveTypesByOrganizationResponse.items:type_name -> query.incident.classifier.v1.Type
	1,  // 7: query.incident.classifier.v1.ListPatientAllowedTypesByOrganizationResponse.items:type_name -> query.incident.classifier.v1.Type
	0,  // 8: query.incident.classifier.v1.ListPatientVisibleCategoriesByOrganizationResponse.items:type_name -> query.incident.classifier.v1.Category
	2,  // 9: query.incident.classifier.v1.IncidentClassifierQueryService.GetCategory:input_type -> query.incident.classifier.v1.GetCategoryRequest
	4,  // 10: query.incident.classifier.v1.IncidentClassifierQueryService.ListCategoriesByOrganization:input_type -> query.incident.classifier.v1.ListCategoriesByOrganizationRequest
	6,  // 11: query.incident.classifier.v1.IncidentClassifierQueryService.ListActiveRootCategories:input_type -> query.incident.classifier.v1.ListActiveRootCategoriesRequest
	8,  // 12: query.incident.classifier.v1.IncidentClassifierQueryService.ListCategorySubtree:input_type -> query.incident.classifier.v1.ListCategorySubtreeRequest
	10, // 13: query.incident.classifier.v1.IncidentClassifierQueryService.GetType:input_type -> query.incident.classifier.v1.GetTypeRequest
	12, // 14: query.incident.classifier.v1.IncidentClassifierQueryService.ListTypesByCategory:input_type -> query.incident.classifier.v1.ListTypesByCategoryRequest
	14, // 15: query.incident.classifier.v1.IncidentClassifierQueryService.ListActiveTypesByOrganization:input_type -> query.incident.classifier.v1.ListActiveTypesByOrganizationRequest
	16, // 16: query.incident.classifier.v1.IncidentClassifierQueryService.ListPatientAllowedTypesByOrganization:input_type -> query.incident.classifier.v1.ListPatientAllowedTypesByOrganizationRequest
	18, // 17: query.incident.classifier.v1.IncidentClassifierQueryService.ListPatientVisibleCategoriesByOrganization:input_type -> query.incident.classifier.v1.ListPatientVisibleCategoriesByOrganizationRequest
	3,  // 18: query.incident.classifier.v1.IncidentClassifierQueryService.GetCategory:output_type -> query.incident.classifier.v1.GetCategoryResponse
	5,  // 19: query.incident.classifier.v1.IncidentClassifierQueryService.ListCategoriesByOrganization:output_type -> query.incident.classifier.v1.ListCategoriesByOrganizationResponse
	7,  // 20: query.incident.classifier.v1.IncidentClassifierQueryService.ListActiveRootCategories:output_type -> query.incident.classifier.v1.ListActiveRootCategoriesResponse
	9,  // 21: query.incident.classifier.v1.IncidentClassifierQueryService.ListCategorySubtree:output_type -> query.incident.classifier.v1.ListCategorySubtreeResponse
	11, // 22: query.incident.classifier.v1.IncidentClassifierQueryService.GetType:output_type -> query.incident.classifier.v1.GetTypeResponse
	13, // 23: query.incident.classifier.v1.IncidentClassifierQueryService.ListTypesByCategory:output_type -> query.incident.classifier.v1.ListTypesByCategoryResponse
	15, // 24: query.incident.classifier.v1.IncidentClassifierQueryService.ListActiveTypesByOrganization:output_type -> query.incident.classifier.v1.ListActiveTypesByOrganizationResponse
	17, // 25: query.incident.classifier.v1.IncidentClassifierQueryService.ListPatientAllowedTypesByOrganization:output_type -> query.incident.classifier.v1.ListPatientAllowedTypesByOrganizationResponse
	19, // 26: query.incident.classifier.v1.IncidentClassifierQueryService.ListPatientVisibleCategoriesByOrganization:output_type -> query.incident.classifier.v1.ListPatientVisibleCategoriesByOrganizationResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_query_incident_classifier_v1_classifier_proto_init() }
func file_query_incident_classifier_v1_classifier_proto_init() {
	if File_query_incident_classifier_v1_classifier_proto != nil {
		return
	}
	file_query_incident_classifier_v1_classifier_proto_msgTypes[0].OneofWrappers = []any{}
	file_query_incident_classifier_v1_classifier_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_incident_classifier_v1_classifier_proto_rawDesc), len(file_query_incident_classifier_v1_classifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_query_incident_classifier_v1_classifier_proto_goTypes,
		DependencyIndexes: file_query_incident_classifier_v1_classifier_proto_depIdxs,
		MessageInfos:      file_query_incident_classifier_v1_classifier_proto_msgTypes,
	}.Build()
	File_query_incident_classifier_v1_classifier_proto = out.File
	file_query_incident_classifier_v1_classifier_proto_goTypes = nil
	file_query_incident_classifier_v1_classifier_proto_depIdxs = nil
}
