package membership

// Error codes used throughout the membership service. Grouped by
// concern for readability.
const (
	// Input validation — 422-class.
	ErrCodeEmployeeZitadelUserIDEmpty = "employee_zitadel_user_id_empty"
	ErrCodeEmployeeDepartmentIDEmpty  = "employee_department_id_empty"
	ErrCodeEmployeeIDEmpty            = "employee_id_empty"
	ErrCodeEmployeePositionTooShort   = "employee_position_too_short"
	ErrCodeEmployeePositionTooLong    = "employee_position_too_long"
	ErrCodeVacationIDEmpty            = "vacation_id_empty"
	ErrCodeVacationEndBeforeStart     = "vacation_end_before_start"
	ErrCodeVacationEndInPast          = "vacation_end_in_past"
	ErrCodeVacationStartRequired      = "vacation_start_required"
	ErrCodeVacationStartInPast        = "vacation_start_in_past"

	ErrCodeDepartmentIDEmpty             = "department_id_empty"
	ErrCodeClinicIDEmpty                 = "clinic_id_empty"
	ErrCodeOrganizationIDEmpty           = "organization_id_empty"
	ErrCodeDeputyEmployeeIDEmpty         = "deputy_employee_id_empty"
	ErrCodeSystemAdminZitadelUserIDEmpty = "system_admin_zitadel_user_id_empty"

	// Business preconditions — 409/422-class.
	ErrCodeEmployeeAlreadyHired            = "employee_already_hired"
	ErrCodeEmployeeNotFound                = "employee_not_found"
	ErrCodeDepartmentNotFound              = "department_not_found"
	ErrCodeClinicNotFound                  = "clinic_not_found"
	ErrCodeOrganizationNotFound            = "organization_not_found"
	ErrCodeDepartmentNotInSameOrganization = "department_not_in_same_organization"
	ErrCodeVacationNotFound                = "vacation_not_found"
	ErrCodeVacationOverlap                 = "vacation_overlap"
	ErrCodeVacationAlreadyEnded            = "vacation_already_ended"
	ErrCodeVacationNotStarted              = "vacation_not_started"
	ErrCodeVacationAlreadyStarted          = "vacation_already_started"
	ErrCodeZitadelUserNotFound             = "zitadel_user_not_found"

	ErrCodeEmployeeNotInDepartment               = "employee_not_in_department"
	ErrCodeEmployeeNotInClinic                   = "employee_not_in_clinic"
	ErrCodeEmployeeNotInOrganization             = "employee_not_in_organization"
	ErrCodeDepartmentResponsibleAlreadyAssigned  = "department_responsible_already_assigned"
	ErrCodeDepartmentResponsibleNotFound         = "department_responsible_not_found"
	ErrCodeClinicHeadAlreadyAssigned             = "clinic_head_already_assigned"
	ErrCodeClinicHeadNotFound                    = "clinic_head_not_found"
	ErrCodeOrganizationAdminAlreadyAssigned      = "organization_admin_already_assigned"
	ErrCodeOrganizationAdminNotFound             = "organization_admin_not_found"
	ErrCodeOrganizationHeadAlreadyAssigned       = "organization_head_already_assigned"
	ErrCodeOrganizationHeadNotFound              = "organization_head_not_found"
	ErrCodeOrganizationDispatcherAlreadyAssigned = "organization_dispatcher_already_assigned"
	ErrCodeOrganizationDispatcherNotFound        = "organization_dispatcher_not_found"
	ErrCodeSystemAdminAlreadyGranted             = "system_admin_already_granted"
	ErrCodeSystemAdminNotFound                   = "system_admin_not_found"
	ErrCodeDeputyNotFound                        = "deputy_not_found"
	ErrCodeDeputyNotInDepartment                 = "deputy_not_in_department"
	ErrCodeDeputyNotInClinic                     = "deputy_not_in_clinic"
	ErrCodeDeputyNotInOrganization               = "deputy_not_in_organization"
	ErrCodeDeputyIsHolder                        = "deputy_is_holder"
	ErrCodeDeputyAlreadyAssigned                 = "deputy_already_assigned"
	ErrCodeDeputyNotAssigned                     = "deputy_not_assigned"

	// Infrastructure — 500-class.
	ErrCodeEmployeeIDGenerationFailed = "employee_id_generation_failed"
	ErrCodeEmployeeSaveFailed         = "employee_save_failed"
	ErrCodeEmployeeLoadFailed         = "employee_load_failed"
	ErrCodeEmployeeDeleteFailed       = "employee_delete_failed"
	ErrCodeEmployeeEventBuildFailed   = "employee_event_build_failed"
	ErrCodeVacationIDGenerationFailed = "vacation_id_generation_failed"
	ErrCodeVacationSaveFailed         = "vacation_save_failed"
	ErrCodeVacationLoadFailed         = "vacation_load_failed"
	ErrCodeVacationDeleteFailed       = "vacation_delete_failed"
	ErrCodeVacationEventBuildFailed   = "vacation_event_build_failed"
	ErrCodeDepartmentLookupFailed     = "department_lookup_failed"
	ErrCodeClinicLookupFailed         = "clinic_lookup_failed"
	ErrCodeOrganizationLookupFailed   = "organization_lookup_failed"
	// Zitadel verify failures are emitted via
	// services/zitadel.ErrCodeZitadelVerifyFailed — do not re-declare
	// the string here so the two constants can't drift apart.

	ErrCodeDepartmentResponsibleSaveFailed        = "department_responsible_save_failed"
	ErrCodeDepartmentResponsibleLoadFailed        = "department_responsible_load_failed"
	ErrCodeDepartmentResponsibleDeleteFailed      = "department_responsible_delete_failed"
	ErrCodeDepartmentResponsibleEventBuildFailed  = "department_responsible_event_build_failed"
	ErrCodeClinicHeadSaveFailed                   = "clinic_head_save_failed"
	ErrCodeClinicHeadLoadFailed                   = "clinic_head_load_failed"
	ErrCodeClinicHeadDeleteFailed                 = "clinic_head_delete_failed"
	ErrCodeClinicHeadEventBuildFailed             = "clinic_head_event_build_failed"
	ErrCodeOrganizationAdminSaveFailed            = "organization_admin_save_failed"
	ErrCodeOrganizationAdminLoadFailed            = "organization_admin_load_failed"
	ErrCodeOrganizationAdminDeleteFailed          = "organization_admin_delete_failed"
	ErrCodeOrganizationAdminEventBuildFailed      = "organization_admin_event_build_failed"
	ErrCodeOrganizationHeadSaveFailed             = "organization_head_save_failed"
	ErrCodeOrganizationHeadLoadFailed             = "organization_head_load_failed"
	ErrCodeOrganizationHeadDeleteFailed           = "organization_head_delete_failed"
	ErrCodeOrganizationHeadEventBuildFailed       = "organization_head_event_build_failed"
	ErrCodeOrganizationDispatcherSaveFailed       = "organization_dispatcher_save_failed"
	ErrCodeOrganizationDispatcherLoadFailed       = "organization_dispatcher_load_failed"
	ErrCodeOrganizationDispatcherDeleteFailed     = "organization_dispatcher_delete_failed"
	ErrCodeOrganizationDispatcherEventBuildFailed = "organization_dispatcher_event_build_failed"
	ErrCodeSystemAdminSaveFailed                  = "system_admin_save_failed"
	ErrCodeSystemAdminDeleteFailed                = "system_admin_delete_failed"
	ErrCodeSystemAdminEventBuildFailed            = "system_admin_event_build_failed"
)
